# Model quality estimation

## Task 1. Answer the questions from the introduction
1. What is leave-one-out? Provide limitations and strengths.
  
    Answer: Leave-One-Out cross-validator provides train/test indices to split data in train/test sets. <b>Each sample is used once as a test set</b> (singleton) while the remaining samples form the training set.

    <b>Strengths</b>:
    * Maximum use of data.
    * Preservation of data distribution.
    * Suitable for very small datasets.

    <b>Limitations</b>:
    * High computational complexity.
    * High variance in model performance evaluation.
    * Sensitivity to outliers.
    * Risk of overfitting.
    * Risk of data leakage.
2. How do Grid Search, Randomized Grid Search, and Bayesian optimization work?

    <b>Grid Search</b>: In grid search, the algorithm tries all possible combinations of parameters; after evaluating all combinations, the algorithm selects the combination of parameters that yields the best result according to the evaluation function.

    <b>Randomized Grid Search</b>: In a randomized grid search, the method generates a fixed number of random combinations of hyperparameters by selecting values from specified distributions. For each randomly selected combination of hyperparameters, the model is trained, and its performance is evaluated using a selected metric via cross-validation.

    <b>Bayesian optimization</b>: In Bayesian optimization, initial points are first determined; at each iteration, the probabilistic model is updated based on new data (objective function values at the selected points). An acquisition function is used to determine the point at which the objective function value should be computed next. This point maximizes the objective.  The process is repeated until a specified stopping criterion is met.

3. Explain classification of feature selection methods. Explain how Pearson and Chi2 work. Explain how Lasso works. Explain what permutation significance is. Become familiar with SHAP.

    <b>Pearson</b>: Pearson's correlation coefficient is designed to detect only linear relationships between variables. Pearson's correlation requires that each of the variables being compared be normally distributed. The Pearson correlation coefficient ranges from −1 to +1:
    * +1 — perfect positive correlation (when the value of one variable increases, the value of the other also increases);
    * 0 — no linear correlation;
    * -1 — perfect negative correlation (when the value of one variable increases, the value of the other decreases).

    <b>Chi2</b>: The chi-square test measures the difference between the observed and expected frequencies of categories under the null hypothesis that the variables are independent. The null hypothesis assumes that two categorical variables are independent. The alternative hypothesis is that there is a relationship between the variable and the response variable.

    <b>Lasso</b>: Lasso modifies the objective function (for example, in linear regression) by adding a term that represents the L1 norm of the coefficient vector—the sum of the absolute values of the coefficients. This results in some coefficients being set to zero, which allows the method to perform feature selection.

    <b>Permutation significance</b>: The basic idea behind the method is to generate a "zero" distribution by randomly shuffling the data. This assumes that there are no significant correlations or differences between the variables or groups.
    
    How it works:
      * The original data is divided into two samples.
      * A test statistic is selected that captures the essence of the hypothesis being tested.
      * The values or data groups are randomly shuffled while preserving the structure of the variables.
      * Steps 2 and 3 are repeated many times (often 1,000–10,000 times) to construct a null distribution of the test statistic.
      * Comparing the original test statistic with the null distribution determines the proportion of permutations in which the test statistic was as extreme or more extreme than the observed value.

## Task 2. Introduction — do all the preprocessing from the previous lesson
* Read all the data.

In [1]:
%pip install optuna

Collecting optuna
  Downloading optuna-4.8.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.48)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.3.2)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.8.0-py3-none-any.whl (419 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 419.5/419.5 kB 10.8 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.8.0

In [51]:
import numpy as np
import pandas as pd

import time
from collections import Counter
import itertools
from tqdm import tqdm

from sklearn.model_selection import KFold, GroupKFold, StratifiedKFold, TimeSeriesSplit, cross_val_score
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import Lasso, ElasticNet
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score, make_scorer

import shap

import optuna
from optuna.samplers import TPESampler

In [3]:
data = pd.read_json('data/train.json')

* Create features: 'Elevator', 'HardwoodFloors', 'CatsAllowed', 'DogsAllowed', 'Doorman', 'Dishwasher', 'NoFee', 'LaundryinBuilding', 'FitnessCenter', 'Pre-War', 'LaundryinUnit', 'RoofDeck', 'OutdoorSpace', 'DiningRoom', 'HighSpeedInternet', 'Balcony', 'SwimmingPool', 'LaundryInBuilding', 'NewConstruction', 'Terrace'.

In [4]:
low, high = np.percentile(data['price'], [1, 99])

data = data[(data['price'] >= low) & (data['price'] <= high)]

In [5]:
data.features = data.features.apply(lambda x: ','.join(x).replace(' ', ''))

features_list = []

for _, row in data.iterrows():
  curr = row.features.split(',')
  if curr != ['']:
    features_list.extend(curr)

counter = Counter(features_list)

features = counter.most_common(20)
features_df = pd.DataFrame()

for f in features:
  features_df[f[0]] = data.features.apply(lambda x: int(f[0] in x.split(',')))

features_df['bathrooms'] = data.bathrooms
features_df['bedrooms'] = data.bedrooms

features_df.head()

,Elevator,HardwoodFloors,CatsAllowed,DogsAllowed,Doorman,Dishwasher,NoFee,LaundryinBuilding,FitnessCenter,Pre-War,...,OutdoorSpace,DiningRoom,HighSpeedInternet,Balcony,SwimmingPool,LaundryInBuilding,NewConstruction,Terrace,bathrooms,bedrooms
4,0,1,1,1,0,1,0,1,0,1,...,0,1,0,0,0,0,0,0,1.0,1
6,1,1,0,0,1,1,1,1,0,0,...,0,0,0,0,0,0,0,0,1.0,2
9,1,1,0,0,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,1.0,2
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1.5,3
15,1,0,0,0,1,0,0,1,1,0,...,0,0,0,0,0,0,0,0,1.0,0

## Task 3. Implement the next methods:
* Split data into 2 parts randomly with parameter test_size (ratio from 0 to 1), return training and test samples.

In [6]:
def my_train_test_split(X, y, test_size=0.25, random_state=21):
  rows = len(X)
  test_count = int(np.round(rows * test_size))

  X_train = X.sample(frac=1 - test_size, random_state=random_state)
  y_train = y.iloc[X_train.index]

  X_test = X.drop(X_train.index)
  y_test = y.drop(X_train.index)

  return X_train, y_train, X_test, y_test

* Randomly split data into 3 parts with parameters validation_size and test_size, return train, validation and test samples.

In [7]:
def my_train_validation_test_split(X, y, validation_size=0.25, test_size=0.25, random_state=21):
  rows = len(X)
  np.random.seed(random_state)

  indices = np.random.permutation(rows)

  test_idx = int(len(X) * (1 - test_size))

  val_idx = int(len(X) * (1 - (validation_size + test_size)))

  train_idx = indices[:val_idx]
  val_idx = indices[val_idx:test_idx]
  test_idx = indices[test_idx:]

  return X.iloc[train_idx], y.iloc[train_idx], X.iloc[val_idx], y.iloc[val_idx], X.iloc[test_idx], y.iloc[test_idx]

* Split data into 2 parts with parameter date_split, return train and test samples split by date_split param.

In [8]:
def my_train_test_date_split(X, y, date_column, date_split, random_state=21):
  X[date_column] = pd.to_datetime(X[date_column])
  date_split = pd.to_datetime(date_split)

  train_idx = X[date_column] < date_split
  test_idx = X[date_column] >= date_split

  X_train = X[train_idx]
  y_train = y[train_idx]
  X_test = X[test_idx]
  y_test = y[test_idx]

  return X_train, y_train, X_test, y_test

* Split data into 3 parts with parameters validation_date and test_date, return train, validation and test samples split by input params.

In [9]:
def my_train_validation_test_date_split(X, y, date_column, validation_date, test_date, random_state=21):
  X[date_column] = pd.to_datetime(X[date_column])
  date_split = pd.to_datetime(date_split)

  train_idx = X[date_column] < validation_date
  val_idx = (X[date_column] >= validation_date) & (X[date_column] < test_date)
  test_idx = X[date_column] >= test_date

  X_train = X[train_idx]
  y_train = y[train_idx]
  X_val = X[val_idx]
  y_val = y[val_idx]
  X_test = X[test_idx]
  y_test = y[test_idx]

  return X_train, y_train, X_val, y_val, X_test, y_test

## Task 4. Implement the next cross-validation methods:
* K-Fold, where k is the input parameter, returns a list of train and test indices.

In [10]:
def my_KFold_split(X, k=5, shuffle=False, random_state=None):
  rows = len(X)
  idx = np.arange(rows)
  if shuffle:
    np.random.seed(random_state)
    np.random.shuffle(idx)

  test_splits = np.array_split(idx, k)

  splits = []

  for test_idx in test_splits:
    train_idx = np.setdiff1d(idx, test_idx)
    splits.append((train_idx, test_idx))

  return splits

* Grouped K-Fold, where k and group_field are input parameters, returns list of train and test indices.

In [11]:
def my_Grouped_KFold_split(X, group_field, k=5, shuffle=False, random_state=None):
  rows = len(X)
  idx = np.arange(rows)
  groups = X[group_field].unique()

  if k > len(groups):
    raise ValueError('k must be less than or equal to groupes count')

  if shuffle:
    if random_state is not None:
      np.random.seed(random_state)
    np.random.shuffle(groups)

  test_groups = np.array_split(groups, k)

  splits = []

  for test_group in test_groups:
    mask = X[group_field].isin(test_group)

    test_positions = np.where(mask)[0]
    train_positions = np.where(~mask)[0]

    splits.append((train_positions, test_positions))

  return splits

* Stratified K-fold, where k and stratify_field are input parameters, returns list of train and test indices.

In [12]:
def my_Stratified_KFold_split(X, stratify_field, k=5, shuffle=False, random_state=None):
  if shuffle and random_state:
        np.random.seed(random_state)

  rows = len(X)
  y = X[stratify_field]
  unique_classes = y.unique()

  index_to_position = {idx: pos for pos, idx in enumerate(X.index)}

  class_positions = {}
  for cls in unique_classes:
    original_idx = y[y == cls].index.tolist()
    positions = [index_to_position[idx] for idx in original_idx]

    if shuffle:
      np.random.shuffle(positions)

    class_positions[cls] = positions

  class_folds = {}
  for cls, positions in class_positions.items():
    class_folds[cls] = np.array_split(positions, k)

  splits = []
  all_pos = np.arange(rows)

  for fold in range(k):
    test_positions = []
    for cls in unique_classes:
      test_positions.extend(class_folds[cls][fold])

    test_positions = np.array(test_positions)

    train_positions = np.setdiff1d(all_pos, test_positions)

    splits.append((train_positions, test_positions))

  return splits

* Time series split, where k and date_field are input parameters, returns list of train and test indices.

In [13]:
def my_TimeSeriesSplit(X, date_field, k=5):
  X_sorted = X.sort_values(date_field).reset_index(drop=True)
  rows = len(X_sorted)

  test_size = rows // (k + 1)

  splits = []

  for i in range(1, k + 1):
    test_start = i  * test_size
    test_end = test_start + test_size

    if i == k:
      test_end = rows

    test_positions = np.arange(test_start, test_end)

    train_positions = np.arange(0, test_start)

    if len(train_positions) > 0:
      splits.append((train_positions, test_positions))

  return splits

## Task 5. Cross-validation comparison
* Apply all the validation methods implemented above to our dataset. To apply Stratified algorithm you should preprocess target.

In [14]:
final_df = pd.concat([features_df, data.price], axis=1)

### K-Fold

In [15]:
for i, (train_idx, test_idx) in enumerate(my_KFold_split(final_df, k=5, shuffle=True, random_state=21)):
  print(f'Fold {i+1}')
  print(f'train:\n\t{train_idx}')
  print(f'test:\n\t{test_idx}')

Fold 1
train:
	[    0     1     3 ... 48372 48374 48376]
test:
	[ 1270 37030 29625 ... 47042 46275 39531]
Fold 2
train:
	[    1     2     3 ... 48376 48377 48378]
test:
	[44789  2875 13110 ... 18512   862 21075]
Fold 3
train:
	[    0     1     2 ... 48375 48377 48378]
test:
	[27870 35325 26603 ...  1800 27879 40136]
Fold 4
train:
	[    0     1     2 ... 48376 48377 48378]
test:
	[43094 35046 15003 ...  8653 41042  6238]
Fold 5
train:
	[    0     2     3 ... 48376 48377 48378]
test:
	[34551  6912 30457 ...  5944  5327 15305]

### Grouped K-Fold

In [16]:
for i, (train_idx, test_idx) in enumerate(my_Grouped_KFold_split(final_df, 'bedrooms', k=5, shuffle=True, random_state=21)):
  print(f'Fold {i+1}')
  print(f'train:\n\t{final_df.bedrooms.iloc[train_idx].unique()}')
  print(f'test:\n\t{final_df.bedrooms.iloc[test_idx].unique()}')

Fold 1
train:
	[1 0 4 5 6 8 7]
test:
	[2 3]
Fold 2
train:
	[1 2 3 4 5 6 7]
test:
	[0 8]
Fold 3
train:
	[1 2 3 0 4 8 7]
test:
	[5 6]
Fold 4
train:
	[2 3 0 5 6 8 7]
test:
	[1 4]
Fold 5
train:
	[1 2 3 0 4 5 6 8]
test:
	[7]

## Stratified K-Fold

In [17]:
bins = [-1, 2500, 4065, 13000]
labels = ['low', 'medium', 'high']

bin_target = pd.cut(final_df.price, bins=bins, labels=labels)

final_df['bin_price'] = bin_target

In [18]:
for i, (train_idx, test_idx) in enumerate(my_Stratified_KFold_split(final_df, 'bin_price', k=3, shuffle=True, random_state=21)):
  train_counts = len(final_df.bin_price.iloc[train_idx])
  test_counts = len(final_df.bin_price.iloc[test_idx])
  print(f'Fold {i+1}')
  print(f'train:\n\t{np.round(final_df.bin_price.iloc[train_idx].value_counts() / train_counts * 100, 2)}')
  print(f'test:\n\t{np.round(final_df.bin_price.iloc[test_idx].value_counts() / test_counts * 100, 2)}\n\n')

Fold 1
train:
	bin_price
medium    48.25
low       26.75
high      25.00
Name: count, dtype: float64
test:
	bin_price
medium    48.25
low       26.75
high      25.00
Name: count, dtype: float64


Fold 2
train:
	bin_price
medium    48.25
low       26.75
high      25.00
Name: count, dtype: float64
test:
	bin_price
medium    48.25
low       26.75
high      25.00
Name: count, dtype: float64


Fold 3
train:
	bin_price
medium    48.25
low       26.75
high      25.00
Name: count, dtype: float64
test:
	bin_price
medium    48.25
low       26.75
high      25.00
Name: count, dtype: float64

### TimeSeriesSplit

In [19]:
final_df['date'] = data.created

In [20]:
sorted_df = final_df.sort_values('date').reset_index(drop=True)

for i, (train_idx, test_idx) in enumerate(my_TimeSeriesSplit(sorted_df, 'date', k=5)):
  print(f'Fold {i+1}')
  print(f'train:\n\tmin: {sorted_df.date.iloc[train_idx].min()} max: {sorted_df.date.iloc[train_idx].max()}')
  print(f'test:\n\tmin: {sorted_df.date.iloc[test_idx].min()} max: {sorted_df.date.iloc[test_idx].max()}')

Fold 1
train:
	min: 2016-04-01 22:12:41 max: 2016-04-16 01:29:59
test:
	min: 2016-04-16 01:30:37 max: 2016-05-02 01:14:08
Fold 2
train:
	min: 2016-04-01 22:12:41 max: 2016-05-02 01:14:08
test:
	min: 2016-05-02 01:14:30 max: 2016-05-16 02:56:35
Fold 3
train:
	min: 2016-04-01 22:12:41 max: 2016-05-16 02:56:35
test:
	min: 2016-05-16 02:56:37 max: 2016-06-01 05:58:11
Fold 4
train:
	min: 2016-04-01 22:12:41 max: 2016-06-01 05:58:11
test:
	min: 2016-06-01 05:58:17 max: 2016-06-15 02:25:53
Fold 5
train:
	min: 2016-04-01 22:12:41 max: 2016-06-15 02:25:53
test:
	min: 2016-06-15 02:26:31 max: 2016-06-29 21:41:47

* Apply the appropriate methods from sklearn.

### K-Fold

In [21]:
kf = KFold(n_splits=5, shuffle=True, random_state=21)
for i, (train_index, test_index) in enumerate(kf.split(final_df)):
    print(f"Fold {i}:")
    print(f"  Train: index={train_index}")
    print(f"  Test:  index={test_index}")

Fold 0:
  Train: index=[    0     1     3 ... 48372 48374 48376]
  Test:  index=[    2     7    21 ... 48375 48377 48378]
Fold 1:
  Train: index=[    1     2     3 ... 48376 48377 48378]
  Test:  index=[    0    11    13 ... 48366 48370 48372]
Fold 2:
  Train: index=[    0     1     2 ... 48375 48377 48378]
  Test:  index=[    4    18    31 ... 48369 48374 48376]
Fold 3:
  Train: index=[    0     1     2 ... 48376 48377 48378]
  Test:  index=[    3     6    14 ... 48358 48362 48367]
Fold 4:
  Train: index=[    0     2     3 ... 48376 48377 48378]
  Test:  index=[    1     5     8 ... 48345 48349 48352]

### Group K-Fold

In [22]:
group_kfold = GroupKFold(n_splits=5, shuffle=True, random_state=21)
groups = final_df['bedrooms']

for i, (train_index, test_index) in enumerate(group_kfold.split(final_df, groups=groups)):
    print(f"Fold {i}:")
    print(f"  Train: group={groups.iloc[train_index].unique()}")
    print(f"  Test:  group={groups.iloc[test_index].unique()}")

Fold 0:
  Train: group=[3 0 4 5 6 8 7]
  Test:  group=[1 2]
Fold 1:
  Train: group=[1 2 0 4 5 6 8]
  Test:  group=[3 7]
Fold 2:
  Train: group=[1 2 3 0 4 8 7]
  Test:  group=[5 6]
Fold 3:
  Train: group=[1 2 3 5 6 8 7]
  Test:  group=[0 4]
Fold 4:
  Train: group=[1 2 3 0 4 5 6 7]
  Test:  group=[8]

### Stratified K-Fold

In [23]:
skf = StratifiedKFold(n_splits=2, shuffle=True, random_state=21)
y_bin = final_df['bin_price']

for i, (train_index, test_index) in enumerate(skf.split(final_df, y_bin)):
  train_counts = len(y_bin.iloc[train_idx])
  test_counts = len(y_bin.iloc[test_idx])
  print(f'Fold {i+1}')
  print(f'train:\n\t{np.round(y_bin.iloc[train_idx].value_counts() / train_counts * 100, 2)}')
  print(f'test:\n\t{np.round(y_bin.iloc[test_idx].value_counts() / test_counts * 100, 2)}\n\n')

Fold 1
train:
	bin_price
medium    48.22
low       26.63
high      25.15
Name: count, dtype: float64
test:
	bin_price
medium    48.39
low       27.39
high      24.22
Name: count, dtype: float64


Fold 2
train:
	bin_price
medium    48.22
low       26.63
high      25.15
Name: count, dtype: float64
test:
	bin_price
medium    48.39
low       27.39
high      24.22
Name: count, dtype: float64

### TimeSeriesSplit

In [24]:
tscv = TimeSeriesSplit()

for i, (train_index, test_index) in enumerate(tscv.split(sorted_df)):
  print(f'Fold {i+1}')
  print(f"  Train: index={train_index}")
  print(f"  Test:  index={test_index}")

Fold 1
  Train: index=[   0    1    2 ... 8061 8062 8063]
  Test:  index=[ 8064  8065  8066 ... 16124 16125 16126]
Fold 2
  Train: index=[    0     1     2 ... 16124 16125 16126]
  Test:  index=[16127 16128 16129 ... 24187 24188 24189]
Fold 3
  Train: index=[    0     1     2 ... 24187 24188 24189]
  Test:  index=[24190 24191 24192 ... 32250 32251 32252]
Fold 4
  Train: index=[    0     1     2 ... 32250 32251 32252]
  Test:  index=[32253 32254 32255 ... 40313 40314 40315]
Fold 5
  Train: index=[    0     1     2 ... 40313 40314 40315]
  Test:  index=[40316 40317 40318 ... 48376 48377 48378]

In [25]:
for i, (train_idx, test_idx) in enumerate(my_TimeSeriesSplit(sorted_df, 'date', k=5)):
  print(f'Fold {i+1}')
  print(f"  Train: index={train_idx}")
  print(f"  Test:  index={test_idx}")

Fold 1
  Train: index=[   0    1    2 ... 8060 8061 8062]
  Test:  index=[ 8063  8064  8065 ... 16123 16124 16125]
Fold 2
  Train: index=[    0     1     2 ... 16123 16124 16125]
  Test:  index=[16126 16127 16128 ... 24186 24187 24188]
Fold 3
  Train: index=[    0     1     2 ... 24186 24187 24188]
  Test:  index=[24189 24190 24191 ... 32249 32250 32251]
Fold 4
  Train: index=[    0     1     2 ... 32249 32250 32251]
  Test:  index=[32252 32253 32254 ... 40312 40313 40314]
Fold 5
  Train: index=[    0     1     2 ... 40312 40313 40314]
  Test:  index=[40315 40316 40317 ... 48376 48377 48378]

* Compare the resulting feature distributions for the training part of the dataset between sklearn and your implementation.

### K-Fold

In [26]:
data = []

for i, (train_idx, test_idx) in enumerate(my_KFold_split(final_df, k=5, shuffle=True, random_state=21)):
  for col in final_df.columns:
    if col not in ['bin_price', 'date']:
      my_data = final_df.iloc[train_idx][col]
      stats_my = {
          'fold': i,
          'feature': col + '_my',
          'mean': my_data.mean(),
          'std': my_data.std(),
          'min': my_data.min(),
          'max': my_data.max(),
          'q25': my_data.quantile(0.25),
          'q50': my_data.quantile(0.50),
          'q75': my_data.quantile(0.75)
        }

      data.append(stats_my)

kf = KFold(n_splits=5, shuffle=True, random_state=21)
for i, (train_index, test_index) in enumerate(kf.split(final_df)):

  for col in final_df.columns:
    if col not in ['bin_price', 'date']:
      sk_data = final_df.iloc[train_idx][col]
      stats_sk = {
          'fold': i,
          'feature': col + '_sklearn',
          'mean': sk_data.mean(),
          'std': sk_data.std(),
          'min': sk_data.min(),
          'max': sk_data.max(),
          'q25': sk_data.quantile(0.25),
          'q50': sk_data.quantile(0.50),
          'q75': sk_data.quantile(0.75)
        }
      data.append(stats_sk)

kfold_distr = pd.DataFrame(data).sort_values(by=['fold', 'feature'])

kfold_distr[kfold_distr['fold'] == 0]

,fold,feature,mean,std,min,max,q25,q50,q75
15,0,Balcony_my,0.060409,0.238246,0.0,1.0,0.0,0.0,0.0
130,0,Balcony_sklearn,0.060459,0.238338,0.0,1.0,0.0,0.0,0.0
2,0,CatsAllowed_my,0.477612,0.499505,0.0,1.0,0.0,0.0,1.0
117,0,CatsAllowed_sklearn,0.477909,0.499518,0.0,1.0,0.0,0.0,1.0
13,0,DiningRoom_my,0.101491,0.301981,0.0,1.0,0.0,0.0,0.0
128,0,DiningRoom_sklearn,0.102393,0.303168,0.0,1.0,0.0,0.0,0.0
5,0,Dishwasher_my,0.414051,0.492564,0.0,1.0,0.0,0.0,1.0
120,0,Dishwasher_sklearn,0.415461,0.492808,0.0,1.0,0.0,0.0,1.0
3,0,DogsAllowed_my,0.447020,0.497192,0.0,1.0,0.0,0.0,1.0
118,0,DogsAllowed_sklearn,0.447602,0.497253,0.0,1.0,0.0,0.0,1.0
4,0,Doorman_my,0.422577,0.493976,0.0,1.0,0.0,0.0,1.0
119,0,Doorman_sklearn,0.424349,0.494250,0.0,1.0,0.0,0.0,1.0
0,0,Elevator_my,0.523913,0.499434,0.0,1.0,0.0,1.0,1.0
115,0,Elevator_sklearn,0.526173,0.499321,0.0,1.0,0.0,1.0,1.0
8,0,FitnessCenter_my,0.268403,0.443134,0.0,1.0,0.0,0.0,1.0
123,0,FitnessCenter_sklearn,0.269662,0.443790,0.0,1.0,0.0,0.0,1.0
1,0,HardwoodFloors_my,0.478387,0.499539,0.0,1.0,0.0,0.0,1.0
116,0,HardwoodFloors_sklearn,0.479434,0.499583,0.0,1.0,0.0,0.0,1.0
14,0,HighSpeedInternet_my,0.087358,0.282362,0.0,1.0,0.0,0.0,0.0
129,0,HighSpeedInternet_sklearn,0.088182,0.283563,0.0,1.0,0.0,0.0,0.0
17,0,LaundryInBuilding_my,0.052890,0.223817,0.0,1.0,0.0,0.0,0.0
132,0,LaundryInBuilding_sklearn,0.053457,0.224946,0.0,1.0,0.0,0.0,0.0
7,0,LaundryinBuilding_my,0.331525,0.470767,0.0,1.0,0.0,0.0,1.0
122,0,LaundryinBuilding_sklearn,0.333867,0.471599,0.0,1.0,0.0,0.0,1.0
10,0,LaundryinUnit_my,0.173449,0.378640,0.0,1.0,0.0,0.0,0.0
125,0,LaundryinUnit_sklearn,0.174840,0.379835,0.0,1.0,0.0,0.0,0.0
18,0,NewConstruction_my,0.051185,0.220377,0.0,1.0,0.0,0.0,0.0
133,0,NewConstruction_sklearn,0.051907,0.221842,0.0,1.0,0.0,0.0,0.0
6,0,NoFee_my,0.369765,0.482747,0.0,1.0,0.0,0.0,1.0
121,0,NoFee_sklearn,0.368101,0.482295,0.0,1.0,0.0,0.0,1.0
12,0,OutdoorSpace_my,0.106478,0.308452,0.0,1.0,0.0,0.0,0.0
127,0,OutdoorSpace_sklearn,0.107637,0.309926,0.0,1.0,0.0,0.0,0.0
9,0,Pre-War_my,0.186032,0.389138,0.0,1.0,0.0,0.0,0.0
124,0,Pre-War_sklearn,0.185846,0.388988,0.0,1.0,0.0,0.0,0.0
11,0,RoofDeck_my,0.132186,0.338697,0.0,1.0,0.0,0.0,0.0
126,0,RoofDeck_sklearn,0.132958,0.339534,0.0,1.0,0.0,0.0,0.0
16,0,SwimmingPool_my,0.054440,0.226887,0.0,1.0,0.0,0.0,0.0
131,0,SwimmingPool_sklearn,0.054155,0.226325,0.0,1.0,0.0,0.0,0.0
19,0,Terrace_my,0.045500,0.208402,0.0,1.0,0.0,0.0,0.0
134,0,Terrace_sklearn,0.045525,0.208455,0.0,1.0,0.0,0.0,0.0
20,0,bathrooms_my,1.193693,0.454572,0.0,10.0,1.0,1.0,1.0
135,0,bathrooms_sklearn,1.196711,0.456378,0.0,5.0,1.0,1.0,1.0
21,0,bedrooms_my,1.540940,1.099853,0.0,8.0,1.0,1.0,2.0
136,0,bedrooms_sklearn,1.534699,1.105235,0.0,8.0,1.0,1.0,2.0
22,0,price_my,3540.461205,1598.481142,1475.0,13000.0,2500.0,3150.0,4070.0
137,0,price_sklearn,3536.489226,1598.041255,1475.0,13000.0,2500.0,3150.0,4095.0

* Compare all validation schemes. Choose the best one. Explain your choice.

    K-fold cross-validation is suitable for this task; stratified K-fold cross-validation is useful when the target variable has a long-tail distribution, in which case the variable must be binarized

## Task 6. Feature Selection
* Fit a Lasso regression model with normalized features. Use your method for splitting samples into 3 parts by field created with 60/20/20 ratio — train/validation/test.

In [27]:
def get_metrics(model, X_train, X_val, X_test, y_train, y_val, y_test, name):
  model.fit(X_train, y_train)

  y_train_pred = model.predict(X_train)
  y_val_pred = model.predict(X_val)
  y_test_pred = model.predict(X_test)

  mae_result ={
      'model': name,
      'train': mean_absolute_error(y_train, y_train_pred),
      'valid': mean_absolute_error(y_val, y_val_pred),
      'test': mean_absolute_error(y_test, y_test_pred),
  }

  rmse_result = {
      'model': name,
      'train': root_mean_squared_error(y_train, y_train_pred),
      'valid': root_mean_squared_error(y_val, y_val_pred),
      'test': root_mean_squared_error(y_test, y_test_pred),
  }

  r2_result = {
      'model': name,
      'train': r2_score(y_train, y_train_pred),
      'valid': r2_score(y_val, y_val_pred),
      'test': r2_score(y_test, y_test_pred),
  }

  return mae_result, rmse_result, r2_result

In [28]:
final_df = final_df.drop(['bin_price'], axis=1)

In [29]:
final_df.rename(columns={'date': 'created'}, inplace=True)

In [30]:
sorted_df = final_df.sort_values('created').reset_index(drop=True).copy()
X = sorted_df.drop(['price', 'created'], axis=1).copy()
y = sorted_df['price'].copy()

X_train, y_train, X_val, y_val, X_test, y_test = my_train_validation_test_split(X, y, validation_size=0.2, test_size=0.2, random_state=21)

In [31]:
features_to_scale = ['bedrooms', 'bathrooms']

numerical_transformer = ColumnTransformer(
    transformers=[
        ('scaler', MinMaxScaler(), features_to_scale)
    ],
    remainder='passthrough'
)

numerical_transformer.fit(X_train)

X_train_scaled = numerical_transformer.transform(X_train)
X_val_scaled = numerical_transformer.transform(X_val)
X_test_scaled = numerical_transformer.transform(X_test)

In [32]:
lasso_model = Lasso()

mae, rmse, r2 = get_metrics(lasso_model, X_train_scaled, X_val_scaled, X_test_scaled, y_train, y_val, y_test, 'Lasso MinMaxScaler')

mae_result = [mae]

rmse_result = [rmse]

r2_result = [r2]

* Sort features by weight coefficients from model, fit model to top 10 features and compare quality.

In [33]:
feature_names = [x.split('__')[1] for x in numerical_transformer.get_feature_names_out()]

top_10_features = pd.DataFrame(np.abs(lasso_model.coef_), feature_names, columns=['weight']).sort_values('weight', ascending=False).head(10)

top_10_features

                        weight
bathrooms          6315.213474
bedrooms           3634.052484
Doorman             612.350342
LaundryinUnit       460.292979
LaundryInBuilding   334.053415
FitnessCenter       242.633769
Elevator            226.198078
LaundryinBuilding   222.859173
HighSpeedInternet   221.172753
HardwoodFloors      171.941605

In [34]:
X_train_top_10_scaled = numerical_transformer.fit_transform(X_train[top_10_features.index])
X_val_top_10_scaled = numerical_transformer.transform(X_val[top_10_features.index])
X_test_top_10_scaled = numerical_transformer.transform(X_test[top_10_features.index])

mae, rmse, r2 = get_metrics(lasso_model, X_train_top_10_scaled, X_val_top_10_scaled, X_test_top_10_scaled, y_train, y_val, y_test, 'Lasso top10 MinMaxScaler')

mae_result.append(mae)

rmse_result.append(rmse)

r2_result.append(r2)

In [35]:
pd.DataFrame(mae_result)

                      model       train       valid        test
0        Lasso MinMaxScaler  718.020991  699.627626  708.547348
1  Lasso top10 MinMaxScaler  721.948946  702.591138  712.520169

In [35]:
pd.DataFrame(rmse_result)

                      model        train        valid         test
0        Lasso MinMaxScaler  1042.813616  1020.104956  1029.388570
1  Lasso top10 MinMaxScaler  1048.584488  1025.830884  1035.227789

In [36]:
pd.DataFrame(r2_result)

                      model     train     valid      test
0        Lasso MinMaxScaler  0.581429  0.565065  0.588243
1  Lasso top10 MinMaxScaler  0.576784  0.560168  0.583558

* Implement method for simple feature selection by nan-ratio in feature and correlation. Apply this method to feature set and take top 10 features, refit model and measure quality.

In [36]:
def select_features(X, y, k=10, nan_threshold=0.5):
  nan_ratio = X.isnull().mean()

  non_nan_features = nan_ratio[nan_ratio <= nan_threshold].index.to_list()

  X_selected = X[non_nan_features]

  selected_features = np.abs(X_selected.corrwith(y)).nlargest(k).index.to_list()

  return selected_features

In [37]:
selected_features = select_features(X_train, y_train, k=10)

X_train_top_10_selected = numerical_transformer.fit_transform(X_train[selected_features])
X_val_top_10_selected = numerical_transformer.transform(X_val[selected_features])
X_test_top_10_selected = numerical_transformer.transform(X_test[selected_features])

mae, rmse, r2 = get_metrics(lasso_model, X_train_top_10_selected, X_val_top_10_selected, X_test_top_10_selected, y_train, y_val, y_test, 'Lasso selected MinMaxScaler')

mae_result.append(mae)

rmse_result.append(rmse)

r2_result.append(r2)

In [38]:
display(pd.DataFrame(mae_result))
display(pd.DataFrame(rmse_result))
display(pd.DataFrame(r2_result))

                         model       train       valid        test
0           Lasso MinMaxScaler  718.020991  699.627626  708.547348
1     Lasso top10 MinMaxScaler  721.948946  702.591138  712.520169
2  Lasso selected MinMaxScaler  728.618182  710.274463  720.935460

                         model        train        valid         test
0           Lasso MinMaxScaler  1042.813616  1020.104956  1029.388570
1     Lasso top10 MinMaxScaler  1048.584488  1025.830884  1035.227789
2  Lasso selected MinMaxScaler  1055.403770  1033.267363  1040.900072

                         model     train     valid      test
0           Lasso MinMaxScaler  0.581429  0.565065  0.588243
1     Lasso top10 MinMaxScaler  0.576784  0.560168  0.583558
2  Lasso selected MinMaxScaler  0.571261  0.553768  0.578982

* Implement permutation importance method and take top 10 features, refit model and measure quality.

In [39]:
def select_features_permutation(model, X, y, metric=r2_score, k=10, random_state=21):
  np.random.seed(random_state)
  model.fit(X, y)
  base_metric = metric(y, model.predict(X))
  result = []
  for col in X.columns:
    X_permuted = X.copy()
    X_permuted[col] = np.random.permutation(X[col].values)

    permuted_metric = metric(y, model.predict(X_permuted))

    importance = np.abs(base_metric - permuted_metric)

    result.append({
        'feature': col,
        'importance': importance
    })

  return pd.DataFrame(result).sort_values('importance', ascending=False).head(k)

In [40]:
permutation_features = select_features_permutation(lasso_model, X_train, y_train, metric=mean_absolute_error)['feature'].values

X_train_top_10_permutation = numerical_transformer.fit_transform(X_train[permutation_features])
X_val_top_10_permutation = numerical_transformer.transform(X_val[permutation_features])
X_test_top_10_permutation = numerical_transformer.transform(X_test[permutation_features])

mae, rmse, r2 = get_metrics(lasso_model, X_train_top_10_permutation, X_val_top_10_permutation, X_test_top_10_permutation, y_train, y_val, y_test, 'Lasso permutation MinMaxScaler')

mae_result.append(mae)

rmse_result.append(rmse)

r2_result.append(r2)

In [41]:
display(pd.DataFrame(mae_result))
display(pd.DataFrame(rmse_result))
display(pd.DataFrame(r2_result))

                            model       train       valid        test
0              Lasso MinMaxScaler  718.020991  699.627626  708.547348
1        Lasso top10 MinMaxScaler  721.948946  702.591138  712.520169
2     Lasso selected MinMaxScaler  728.618182  710.274463  720.935460
3  Lasso permutation MinMaxScaler  723.149557  705.769389  713.728371

                            model        train        valid         test
0              Lasso MinMaxScaler  1042.813616  1020.104956  1029.388570
1        Lasso top10 MinMaxScaler  1048.584488  1025.830884  1035.227789
2     Lasso selected MinMaxScaler  1055.403770  1033.267363  1040.900072
3  Lasso permutation MinMaxScaler  1049.370481  1027.798426  1035.053759

                            model     train     valid      test
0              Lasso MinMaxScaler  0.581429  0.565065  0.588243
1        Lasso top10 MinMaxScaler  0.576784  0.560168  0.583558
2     Lasso selected MinMaxScaler  0.571261  0.553768  0.578982
3  Lasso permutation MinMaxScaler  0.576149  0.558479  0.583698

* Import Shap and also refit model on top 10 features.

In [42]:
lasso_model.fit(X_train, y_train)

explainer = shap.Explainer(lasso_model, X_train)

shap_values = explainer(X_val)

shap_importance = np.abs(shap_values.values).mean(axis=0)

importance_df = pd.DataFrame({
    'feature': X_val.columns,
    'shap_importance': shap_importance
})

top_10 = importance_df.sort_values('shap_importance', ascending=False).head(10).feature.values

In [43]:
def select_features_shap(model, X_train, y_train, X_val, k=10):
  model.fit(X_train, y_train)

  explainer = shap.Explainer(model, X_train)

  shap_values = explainer(X_val)

  shap_importance = np.abs(shap_values.values).mean(axis=0)

  importance_df = pd.DataFrame({
      'feature': X_val.columns,
      'shap_importance': shap_importance
  })

  top_10 = importance_df.sort_values('shap_importance', ascending=False).head(10).feature.values
  return top_10

In [44]:
X_train_top_10_shap = numerical_transformer.fit_transform(X_train[top_10])
X_val_top_10_shap = numerical_transformer.transform(X_val[top_10])
X_test_top_10_shap = numerical_transformer.transform(X_test[top_10])

mae, rmse, r2 = get_metrics(lasso_model, X_train_top_10_shap, X_val_top_10_shap, X_test_top_10_shap, y_train, y_val, y_test, 'Lasso Shap MinMaxScaler')

mae_result.append(mae)

rmse_result.append(rmse)

r2_result.append(r2)

In [45]:
display(pd.DataFrame(mae_result))
display(pd.DataFrame(rmse_result))
display(pd.DataFrame(r2_result))

                            model       train       valid        test
0              Lasso MinMaxScaler  718.020991  699.627626  708.547348
1        Lasso top10 MinMaxScaler  721.948946  702.591138  712.520169
2     Lasso selected MinMaxScaler  728.618182  710.274463  720.935460
3  Lasso permutation MinMaxScaler  723.149557  705.769389  713.728371
4         Lasso Shap MinMaxScaler  723.641017  706.368279  714.045588

                            model        train        valid         test
0              Lasso MinMaxScaler  1042.813616  1020.104956  1029.388570
1        Lasso top10 MinMaxScaler  1048.584488  1025.830884  1035.227789
2     Lasso selected MinMaxScaler  1055.403770  1033.267363  1040.900072
3  Lasso permutation MinMaxScaler  1049.370481  1027.798426  1035.053759
4         Lasso Shap MinMaxScaler  1050.173022  1028.177913  1035.355058

                            model     train     valid      test
0              Lasso MinMaxScaler  0.581429  0.565065  0.588243
1        Lasso top10 MinMaxScaler  0.576784  0.560168  0.583558
2     Lasso selected MinMaxScaler  0.571261  0.553768  0.578982
3  Lasso permutation MinMaxScaler  0.576149  0.558479  0.583698
4         Lasso Shap MinMaxScaler  0.575500  0.558153  0.583455

* Compare the quality of these methods for different aspects — speed, metrics and stability.

In [46]:
def select_features_lasso(model, X, k=10):
  importance = np.abs(model.coef_)
  importance_df = pd.Series(importance, index=X.columns)
  return importance_df.nlargest(k).index.tolist()

In [47]:
def compare_speed(X_train, y_train, X_val):

    model = Lasso()
    model.fit(X_train, y_train)

    methods = {
        'Correlation': lambda: select_features(X_train, y_train, k=10),
        'Permutation': lambda: select_features_permutation(model, X_train, y_train, k=10),
        'SHAP': lambda: select_features_shap(model, X_train, y_train, X_val, k=10),
        'Lasso Coef': lambda: select_features_lasso(model, X_train, k=10)
    }

    speed_results = []

    for name, method in methods.items():
        start_time = time.time()
        selected = method()
        elapsed_time = time.time() - start_time
        speed_results.append({
            'Method': name,
            'Time (seconds)': elapsed_time,
            'Selected Features': len(selected)
        })

    return pd.DataFrame(speed_results)

In [48]:
compare_speed(X_train, y_train, X_val)

        Method  Time (seconds)  Selected Features
0  Correlation        0.027751                 10
1  Permutation        0.260423                 10
2         SHAP        0.381900                 10
3   Lasso Coef        0.000879                 10

## Task 7. Hyperparameter optimization
* Implement grid search and random search methods for alpha and l1_ratio for sklearn's ElasticNet model

In [103]:
def myGridSearch(model, param_grid, X, y, metric=r2_score, random_state=21):
  result = []
  keys = param_grid.keys()
  values = param_grid.values()
  combinations = list(itertools.product(*values))
  scorer = make_scorer(metric)

  model_results = []
  for combination in tqdm(combinations):
    params = dict(zip(keys, combination))
    model_instance = model(**params)
    kf = KFold(n_splits=5, shuffle=True, random_state=random_state)
    scores = cross_val_score(model_instance, X, y, cv=kf, scoring=scorer)

    model_results.append({
        'params': params,
        'mean_score': np.mean(scores),
        'std_score': np.std(scores)
    })

  return model_results

In [104]:
def myRandomGridSearch(model, param_grid, X, y, n_iter=20, metric=r2_score, random_state=21):
  np.random.seed(random_state)
  scorer = make_scorer(metric)
  results = []

  keys = list(param_grid.keys())
  all_values = list(param_grid.values())

  combinations = []
  for _ in range(n_iter):
    combination = [np.random.choice(values) for values in all_values]
    combinations.append(combination)

  for combination in tqdm(combinations, desc="Random Search"):
    params = dict(zip(keys, combination))
    model_instance = model(**params)

    kf = KFold(n_splits=5, shuffle=True, random_state=random_state)
    scores = cross_val_score(model_instance, X, y, cv=kf, scoring=scorer)

    results.append({
        'params': params,
        'mean_score': np.mean(scores),
        'std_score': np.std(scores)
    })

  results.sort(key=lambda x: x['mean_score'], reverse=True)

  return results

* Find the best combination of model hyperparameters.

In [105]:
param_grid = {
    'alpha': [0.001, 0.01, 0.05, 0.1, 0.5, 1.0, 2.0, 5.0, 10.0],
    'l1_ratio': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
}

result = myGridSearch(ElasticNet, param_grid, X_train_scaled, y_train, metric=mean_absolute_error)

100%|██████████| 90/90 [00:59<00:00,  1.51it/s]

In [106]:
pd.DataFrame(result).sort_values('mean_score')

                              params   mean_score  std_score
69   {'alpha': 2.0, 'l1_ratio': 1.0}   718.629649   4.926650
59   {'alpha': 1.0, 'l1_ratio': 1.0}   718.676271   4.889844
49   {'alpha': 0.5, 'l1_ratio': 1.0}   718.813782   4.841457
39   {'alpha': 0.1, 'l1_ratio': 1.0}   718.936700   4.824225
29  {'alpha': 0.05, 'l1_ratio': 1.0}   718.959040   4.824918
..                               ...          ...        ...
84  {'alpha': 10.0, 'l1_ratio': 0.5}  1130.366709   5.315704
83  {'alpha': 10.0, 'l1_ratio': 0.4}  1133.017171   5.370615
82  {'alpha': 10.0, 'l1_ratio': 0.3}  1135.008782   5.406171
81  {'alpha': 10.0, 'l1_ratio': 0.2}  1136.562017   5.434270
80  {'alpha': 10.0, 'l1_ratio': 0.1}  1137.809036   5.457443

[90 rows x 3 columns]

In [107]:
random_result = myRandomGridSearch(ElasticNet, param_grid, X_train_scaled, y_train)

Random Search: 100%|██████████| 20/20 [00:05<00:00,  3.45it/s]

In [109]:
pd.DataFrame(result).sort_values('mean_score')

                              params   mean_score  std_score
69   {'alpha': 2.0, 'l1_ratio': 1.0}   718.629649   4.926650
59   {'alpha': 1.0, 'l1_ratio': 1.0}   718.676271   4.889844
49   {'alpha': 0.5, 'l1_ratio': 1.0}   718.813782   4.841457
39   {'alpha': 0.1, 'l1_ratio': 1.0}   718.936700   4.824225
29  {'alpha': 0.05, 'l1_ratio': 1.0}   718.959040   4.824918
..                               ...          ...        ...
84  {'alpha': 10.0, 'l1_ratio': 0.5}  1130.366709   5.315704
83  {'alpha': 10.0, 'l1_ratio': 0.4}  1133.017171   5.370615
82  {'alpha': 10.0, 'l1_ratio': 0.3}  1135.008782   5.406171
81  {'alpha': 10.0, 'l1_ratio': 0.2}  1136.562017   5.434270
80  {'alpha': 10.0, 'l1_ratio': 0.1}  1137.809036   5.457443

[90 rows x 3 columns]

* Fit the resulting model.

In [110]:
best_params = result[0]['params']

elastic_model = ElasticNet(**best_params)

mae, rmse, r2 = get_metrics(elastic_model, X_train_scaled, X_val_scaled, X_test_scaled, y_train, y_val, y_test, 'ElasticNet MinMaxScaler')

mae_result.append(mae)

rmse_result.append(rmse)

r2_result.append(r2)

In [111]:
display(pd.DataFrame(mae_result))
display(pd.DataFrame(rmse_result))
display(pd.DataFrame(r2_result))

                            model       train       valid        test
0              Lasso MinMaxScaler  718.020991  699.627626  708.547348
1        Lasso top10 MinMaxScaler  721.948946  702.591138  712.520169
2     Lasso selected MinMaxScaler  728.618182  710.274463  720.935460
3  Lasso permutation MinMaxScaler  723.149557  705.769389  713.728371
4         Lasso Shap MinMaxScaler  723.641017  706.368279  714.045588
5         ElasticNet MinMaxScaler  719.134295  700.584664  709.751940

                            model        train        valid         test
0              Lasso MinMaxScaler  1042.813616  1020.104956  1029.388570
1        Lasso top10 MinMaxScaler  1048.584488  1025.830884  1035.227789
2     Lasso selected MinMaxScaler  1055.403770  1033.267363  1040.900072
3  Lasso permutation MinMaxScaler  1049.370481  1027.798426  1035.053759
4         Lasso Shap MinMaxScaler  1050.173022  1028.177913  1035.355058
5         ElasticNet MinMaxScaler  1043.734289  1019.371044  1031.208091

                            model     train     valid      test
0              Lasso MinMaxScaler  0.581429  0.565065  0.588243
1        Lasso top10 MinMaxScaler  0.576784  0.560168  0.583558
2     Lasso selected MinMaxScaler  0.571261  0.553768  0.578982
3  Lasso permutation MinMaxScaler  0.576149  0.558479  0.583698
4         Lasso Shap MinMaxScaler  0.575500  0.558153  0.583455
5         ElasticNet MinMaxScaler  0.580690  0.565690  0.586786

* Import optuna and configure the same experiment with ElasticNet.

In [53]:
study = optuna.create_study(study_name="my_first_study", directions=["minimize", 'minimize', 'maximize'])

def objective(trial, X, y):
  alpha = trial.suggest_float('alpha', 0.001, 10.0, log=True)
  l1_ratio = trial.suggest_float('l1_ratio', 0.0, 1.0)


  model = ElasticNet(
    alpha=alpha,
    l1_ratio=l1_ratio,
    max_iter=10000,
    random_state=21
  )


  kf = KFold(n_splits=5, shuffle=True, random_state=21)
  scorer = make_scorer(r2_score)
  scores = cross_val_score(model, X, y, cv=kf, scoring=scorer)


  return scores.mean()

study = optuna.create_study(
    direction='maximize',  # максимизируем R²
    sampler=TPESampler(seed=21)  # TPE - алгоритм байесовской оптимизации
)

study.optimize(
    lambda trial: objective(trial, X_train_scaled, y_train),
    n_trials=100,
    show_progress_bar=True
)

[I 2026-04-09 18:38:20,495] A new study created in memory with name: my_first_study
[I 2026-04-09 18:38:20,504] A new study created in memory with name: no-name-d165ab8c-6351-4831-ab2e-cf4a78918b18

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-09 18:38:27,008] Trial 0 finished with value: 0.5788408417876443 and parameters: {'alpha': 0.001566388634308505, 'l1_ratio': 0.28910965978981684}. Best is trial 0 with value: 0.5788408417876443.
[I 2026-04-09 18:38:27,195] Trial 1 finished with value: 0.11711185748534378 and parameters: {'alpha': 0.7653593415503201, 'l1_ratio': 0.021616249915949792}. Best is trial 0 with value: 0.5788408417876443.
[I 2026-04-09 18:38:28,349] Trial 2 finished with value: 0.5563153813921051 and parameters: {'alpha': 0.006663325994391817, 'l1_ratio': 0.0507732566953768}. Best is trial 0 with value: 0.5788408417876443.
[I 2026-04-09 18:38:29,020] Trial 3 finished with value: 0.5610518861029339 and parameters: {'alpha': 0.016184063577845232, 'l1_ratio': 0.6639102946247}. Best is trial 0 with value: 0.5788408417876443.
[I 2026-04-09 18:38:30,425] Trial 4 finished with value: 0.5519553449841693 and parameters: {'alpha': 0.017078808657853408, 'l1_ratio': 0.5835912762185987}. Best is trial 0 with value: 0.5788408417876443.
[I 2026-04-09 18:38:32,252] Trial 5 finished with value: 0.5800192375845571 and parameters: {'alpha': 0.0018979458542442303, 'l1_ratio': 0.8674044839930883}. Best is trial 5 with value: 0.5800192375845571.
[I 2026-04-09 18:38:33,285] Trial 6 finished with value: 0.5735074199651052 and parameters: {'alpha': 0.0034116311964428993, 'l1_ratio': 0.17812466155949835}. Best is trial 5 with value: 0.5800192375845571.
[I 2026-04-09 18:38:33,646] Trial 7 finished with value: 0.5176417813805952 and parameters: {'alpha': 0.09632038266656852, 'l1_ratio': 0.8636996445582236}. Best is trial 5 with value: 0.5800192375845571.
[I 2026-04-09 18:38:33,903] Trial 8 finished with value: 0.4275526513059627 and parameters: {'alpha': 1.0858637674408937, 'l1_ratio': 0.9704851253491577}. Best is trial 5 with value: 0.5800192375845571.
[I 2026-04-09 18:38:34,081] Trial 9 finished with value: 0.12356727066210868 and parameters: {'alpha': 1.089457294703886, 'l1_ratio': 0.3842500320901294}. Best is trial 5 with value: 0.5800192375845571.
[I 2026-04-09 18:38:34,514] Trial 10 finished with value: 0.45785023049708 and parameters: {'alpha': 0.11587772057252048, 'l1_ratio': 0.7835931825968925}. Best is trial 5 with value: 0.5800192375845571.
[I 2026-04-09 18:38:35,959] Trial 11 finished with value: 0.5780919538099252 and parameters: {'alpha': 0.0023849266748819102, 'l1_ratio': 0.39973250796229964}. Best is trial 5 with value: 0.5800192375845571.
[I 2026-04-09 18:38:42,313] Trial 12 finished with value: 0.579535155972549 and parameters: {'alpha': 0.0010123789735895707, 'l1_ratio': 0.27884866501765987}. Best is trial 5 with value: 0.5800192375845571.
[I 2026-04-09 18:38:47,307] Trial 13 finished with value: 0.5798445138779854 and parameters: {'alpha': 0.0010468701483182397, 'l1_ratio': 0.5396389523356229}. Best is trial 5 with value: 0.5800192375845571.
[I 2026-04-09 18:38:47,625] Trial 14 finished with value: 0.4984995798838945 and parameters: {'alpha': 0.057286826194334756, 'l1_ratio': 0.7090655566963474}. Best is trial 5 with value: 0.5800192375845571.
[I 2026-04-09 18:38:47,758] Trial 15 finished with value: 0.03767753497426492 and parameters: {'alpha': 8.695490719982466, 'l1_ratio': 0.5359106125934296}. Best is trial 5 with value: 0.5800192375845571.
[I 2026-04-09 18:38:48,778] Trial 16 finished with value: 0.580069317088739 and parameters: {'alpha': 0.009146586136227519, 'l1_ratio': 0.9892119511047284}. Best is trial 16 with value: 0.580069317088739.
[I 2026-04-09 18:38:49,584] Trial 17 finished with value: 0.580073497192091 and parameters: {'alpha': 0.008605990983240072, 'l1_ratio': 0.9958409935421333}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:38:50,569] Trial 18 finished with value: 0.5799038064680881 and parameters: {'alpha': 0.021968972002211977, 'l1_ratio': 0.9810467299339259}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:38:51,580] Trial 19 finished with value: 0.5792074265324023 and parameters: {'alpha': 0.007226044284866004, 'l1_ratio': 0.8716970517603246}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:38:52,441] Trial 20 finished with value: 0.538725760915505 and parameters: {'alpha': 0.041879636266647896, 'l1_ratio': 0.7747095108565523}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:38:53,565] Trial 21 finished with value: 0.5800730433098575 and parameters: {'alpha': 0.006307491441547687, 'l1_ratio': 0.9962818934273124}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:38:54,889] Trial 22 finished with value: 0.580070363490985 and parameters: {'alpha': 0.0065296937448112565, 'l1_ratio': 0.9861343176156924}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:38:55,698] Trial 23 finished with value: 0.5799291381942242 and parameters: {'alpha': 0.004420721138997192, 'l1_ratio': 0.9121856486181052}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:38:57,585] Trial 24 finished with value: 0.5587244007753163 and parameters: {'alpha': 0.02714870863914764, 'l1_ratio': 0.7836058810098432}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:38:59,309] Trial 25 finished with value: 0.48448359306149 and parameters: {'alpha': 0.2520319081161974, 'l1_ratio': 0.9233261847438927}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:06,281] Trial 26 finished with value: 0.5710444597321103 and parameters: {'alpha': 0.010397461802359866, 'l1_ratio': 0.6738798113189107}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:07,593] Trial 27 finished with value: 0.5796982574133513 and parameters: {'alpha': 0.003915688884767581, 'l1_ratio': 0.8440247804160519}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:08,111] Trial 28 finished with value: 0.5800710942344889 and parameters: {'alpha': 0.2667320458424261, 'l1_ratio': 0.9998272931384737}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:08,376] Trial 29 finished with value: 0.3054826598059576 and parameters: {'alpha': 0.36231900170786463, 'l1_ratio': 0.7608447760468185}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:08,715] Trial 30 finished with value: 0.23496581286275048 and parameters: {'alpha': 2.3844370206086833, 'l1_ratio': 0.9333417795085507}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:09,295] Trial 31 finished with value: 0.5800638195799023 and parameters: {'alpha': 0.20208971726872954, 'l1_ratio': 0.9994675811221742}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:09,959] Trial 32 finished with value: 0.5596859616966413 and parameters: {'alpha': 0.05780677886922149, 'l1_ratio': 0.9016127864746226}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:10,184] Trial 33 finished with value: 0.3163969161001131 and parameters: {'alpha': 0.4458216263627169, 'l1_ratio': 0.8226586600805919}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:11,106] Trial 34 finished with value: 0.5794649244874198 and parameters: {'alpha': 0.012622071657233678, 'l1_ratio': 0.9386305937731574}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:12,455] Trial 35 finished with value: 0.5800729250534653 and parameters: {'alpha': 0.005834443605220082, 'l1_ratio': 0.9895538851137953}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:13,320] Trial 36 finished with value: 0.5792335022662466 and parameters: {'alpha': 0.0024876982041625298, 'l1_ratio': 0.6328246190398281}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:13,859] Trial 37 finished with value: 0.5349315294413499 and parameters: {'alpha': 0.03634568434299126, 'l1_ratio': 0.7221373359835677}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:14,192] Trial 38 finished with value: 0.47683554677360884 and parameters: {'alpha': 0.1198730927213556, 'l1_ratio': 0.8253119681396075}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:15,087] Trial 39 finished with value: 0.5587628204014248 and parameters: {'alpha': 0.006462536388039286, 'l1_ratio': 0.09126302730550179}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:16,945] Trial 40 finished with value: 0.5765009039031613 and parameters: {'alpha': 0.01704470255219196, 'l1_ratio': 0.8841184215353808}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:25,727] Trial 41 finished with value: 0.5799815615391417 and parameters: {'alpha': 0.006564460316427283, 'l1_ratio': 0.9518203637738841}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:27,043] Trial 42 finished with value: 0.5800474849020796 and parameters: {'alpha': 0.004829220154315438, 'l1_ratio': 0.9615163951569498}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:28,041] Trial 43 finished with value: 0.5800729661528126 and parameters: {'alpha': 0.0018070577709166549, 'l1_ratio': 0.9853248129067016}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:29,132] Trial 44 finished with value: 0.5800595706712844 and parameters: {'alpha': 0.0016427906239673, 'l1_ratio': 0.9108268941038987}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:30,374] Trial 45 finished with value: 0.5798439784444454 and parameters: {'alpha': 0.002876230483615403, 'l1_ratio': 0.8323289348659708}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:32,172] Trial 46 finished with value: 0.5800717672497042 and parameters: {'alpha': 0.0017161096654325202, 'l1_ratio': 0.9955729098186281}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:33,339] Trial 47 finished with value: 0.5794414430448187 and parameters: {'alpha': 0.0014641077475968575, 'l1_ratio': 0.4597232378753578}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:34,392] Trial 48 finished with value: 0.5800407279882313 and parameters: {'alpha': 0.0016126646784778182, 'l1_ratio': 0.8734939626592847}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:35,229] Trial 49 finished with value: 0.5757755423936814 and parameters: {'alpha': 0.0029097998490709223, 'l1_ratio': 0.24571842613163625}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:45,027] Trial 50 finished with value: 0.5800728223808078 and parameters: {'alpha': 0.001119358717279708, 'l1_ratio': 0.9465295792776226}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:46,194] Trial 51 finished with value: 0.5800727972013553 and parameters: {'alpha': 0.0011605478327412523, 'l1_ratio': 0.9479324653251783}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:47,282] Trial 52 finished with value: 0.5800724398199486 and parameters: {'alpha': 0.0011931989434063456, 'l1_ratio': 0.9439130020783948}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:48,445] Trial 53 finished with value: 0.5800682655621692 and parameters: {'alpha': 0.002014125120255468, 'l1_ratio': 0.9479588815799074}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:49,710] Trial 54 finished with value: 0.5800659124913436 and parameters: {'alpha': 0.0010064766865236483, 'l1_ratio': 0.8825081301644069}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:50,673] Trial 55 finished with value: 0.579334105424922 and parameters: {'alpha': 0.0042390587910350955, 'l1_ratio': 0.7981193071881315}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:51,977] Trial 56 finished with value: 0.5800335259181517 and parameters: {'alpha': 0.0024121677094691516, 'l1_ratio': 0.9082610320172435}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:52,928] Trial 57 finished with value: 0.5799500260122091 and parameters: {'alpha': 0.010815419194281417, 'l1_ratio': 0.966643859638116}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:53,701] Trial 58 finished with value: 0.5791619065953287 and parameters: {'alpha': 0.003449718707497867, 'l1_ratio': 0.7239408716522497}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:39:57,359] Trial 59 finished with value: 0.5793039560851604 and parameters: {'alpha': 0.005607213285031781, 'l1_ratio': 0.8442849353439574}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:04,453] Trial 60 finished with value: 0.5785080623412251 and parameters: {'alpha': 0.0012670761904218575, 'l1_ratio': 0.003509219861157431}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:05,327] Trial 61 finished with value: 0.5800722312992845 and parameters: {'alpha': 0.0013177780582709607, 'l1_ratio': 0.9468205463632886}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:06,423] Trial 62 finished with value: 0.580071785257021 and parameters: {'alpha': 0.0010106838368603248, 'l1_ratio': 0.9251325062920567}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:08,491] Trial 63 finished with value: 0.5800732274095124 and parameters: {'alpha': 0.0020373598945487687, 'l1_ratio': 0.9766747452790007}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:11,374] Trial 64 finished with value: 0.5800726792385811 and parameters: {'alpha': 0.0021673124824198044, 'l1_ratio': 0.9707492896679087}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:13,446] Trial 65 finished with value: 0.5798501372201474 and parameters: {'alpha': 0.0034040346573389326, 'l1_ratio': 0.8601575234158285}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:24,796] Trial 66 finished with value: 0.5800335345086546 and parameters: {'alpha': 0.008553504687621264, 'l1_ratio': 0.9741739951936713}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:27,136] Trial 67 finished with value: 0.5759805874758405 and parameters: {'alpha': 0.02118989331252372, 'l1_ratio': 0.8994031479129424}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:28,304] Trial 68 finished with value: 0.5800714275704901 and parameters: {'alpha': 0.00418379151171138, 'l1_ratio': 0.9993891759818725}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:29,258] Trial 69 finished with value: 0.5788656631112393 and parameters: {'alpha': 0.013569199857637215, 'l1_ratio': 0.9189357806417112}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:30,375] Trial 70 finished with value: 0.5800166666434171 and parameters: {'alpha': 0.0019997321432479527, 'l1_ratio': 0.871643746087458}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:30,777] Trial 71 finished with value: 0.5800714773145025 and parameters: {'alpha': 0.002152731075326363, 'l1_ratio': 0.963101375461836}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:31,163] Trial 72 finished with value: 0.5800711823912145 and parameters: {'alpha': 0.0029288321231710763, 'l1_ratio': 0.9717937980051942}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:31,626] Trial 73 finished with value: 0.5800688058331784 and parameters: {'alpha': 0.0015450793315856328, 'l1_ratio': 0.9344780887830089}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:31,992] Trial 74 finished with value: 0.5800587830600842 and parameters: {'alpha': 0.005298258124498358, 'l1_ratio': 0.9717841222408721}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:32,422] Trial 75 finished with value: 0.580017900394727 and parameters: {'alpha': 0.0024067175919834727, 'l1_ratio': 0.8943578830267134}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:32,790] Trial 76 finished with value: 0.5633332582292929 and parameters: {'alpha': 0.007708708800587557, 'l1_ratio': 0.3511721667976381}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:33,196] Trial 77 finished with value: 0.5796929472615527 and parameters: {'alpha': 0.0032658316064255377, 'l1_ratio': 0.8116752354284976}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:33,634] Trial 78 finished with value: 0.579394376834631 and parameters: {'alpha': 0.0019164412858196486, 'l1_ratio': 0.5720804254463665}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:33,778] Trial 79 finished with value: 0.4311082400037828 and parameters: {'alpha': 7.6689237664268415, 'l1_ratio': 0.9964857608606729}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:34,203] Trial 80 finished with value: 0.5799722584054636 and parameters: {'alpha': 0.0013162849517051381, 'l1_ratio': 0.7487683140335744}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:34,651] Trial 81 finished with value: 0.580070887888346 and parameters: {'alpha': 0.0014382013372549421, 'l1_ratio': 0.9408675907874923}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:36,320] Trial 82 finished with value: 0.5800727455245436 and parameters: {'alpha': 0.0012506118620129521, 'l1_ratio': 0.9507787626896899}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:38,289] Trial 83 finished with value: 0.5800403943707654 and parameters: {'alpha': 0.002490531752154844, 'l1_ratio': 0.9177642576316734}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:44,694] Trial 84 finished with value: 0.5800732342356961 and parameters: {'alpha': 0.001809642112408179, 'l1_ratio': 0.9743882996236396}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:45,993] Trial 85 finished with value: 0.5800647782041783 and parameters: {'alpha': 0.001193352957393656, 'l1_ratio': 0.8960819972739575}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:46,395] Trial 86 finished with value: 0.5794405630036246 and parameters: {'alpha': 0.005301109053469007, 'l1_ratio': 0.8507763659459467}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:46,858] Trial 87 finished with value: 0.5800703651501106 and parameters: {'alpha': 0.001721516040044139, 'l1_ratio': 0.9479121795837523}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:47,263] Trial 88 finished with value: 0.5800711644674259 and parameters: {'alpha': 0.003855755508517136, 'l1_ratio': 0.9999559032878309}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:47,693] Trial 89 finished with value: 0.5800728353657845 and parameters: {'alpha': 0.0010689744544760229, 'l1_ratio': 0.9773440245219637}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:48,160] Trial 90 finished with value: 0.5800406933704905 and parameters: {'alpha': 0.002626106800846937, 'l1_ratio': 0.9222990488632784}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:48,584] Trial 91 finished with value: 0.580072803004127 and parameters: {'alpha': 0.0010341066728738026, 'l1_ratio': 0.9772280686912961}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:49,030] Trial 92 finished with value: 0.5800725045196655 and parameters: {'alpha': 0.0010624019376592364, 'l1_ratio': 0.9830765737745782}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:49,424] Trial 93 finished with value: 0.5800732519533155 and parameters: {'alpha': 0.0016307152970389649, 'l1_ratio': 0.9736246322307522}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:49,811] Trial 94 finished with value: 0.5800731817599493 and parameters: {'alpha': 0.0017919029111740574, 'l1_ratio': 0.9723104878763721}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:50,249] Trial 95 finished with value: 0.5800732574270956 and parameters: {'alpha': 0.0017962398678719451, 'l1_ratio': 0.9776454846227478}. Best is trial 17 with value: 0.580073497192091.
[I 2026-04-09 18:40:50,650] Trial 96 finished with value: 0.5800732515209994 and parameters: {'alpha': 0.001801333942124324, 'l1_ratio': 0.9753259482334321}. Best is trial 17 with value: 0.580073497192091.

In [56]:
print("Number of finished trials: ", len(study.trials))
print("Best trial:")
trial = study.best_trial

trial.params

Number of finished trials:  100
Best trial:

{'alpha': 0.008605990983240072, 'l1_ratio': 0.9958409935421333}

In [57]:
elastic_model = ElasticNet(**trial.params)

mae, rmse, r2 = get_metrics(elastic_model, X_train_scaled, X_val_scaled, X_test_scaled, y_train, y_val, y_test, 'ElasticNet optuna MinMaxScaler')

mae_result.append(mae)

rmse_result.append(rmse)

r2_result.append(r2)

In [58]:
display(pd.DataFrame(mae_result))
display(pd.DataFrame(rmse_result))
display(pd.DataFrame(r2_result))

                            model       train       valid        test
0              Lasso MinMaxScaler  718.020991  699.627626  708.547348
1        Lasso top10 MinMaxScaler  721.948946  702.591138  712.520169
2     Lasso selected MinMaxScaler  728.618182  710.274463  720.935460
3  Lasso permutation MinMaxScaler  723.149557  705.769389  713.728371
4         Lasso Shap MinMaxScaler  723.641017  706.368279  714.045588
5  ElasticNet optuna MinMaxScaler  718.283708  700.124746  708.777220

                            model        train        valid         test
0              Lasso MinMaxScaler  1042.813616  1020.104956  1029.388570
1        Lasso top10 MinMaxScaler  1048.584488  1025.830884  1035.227789
2     Lasso selected MinMaxScaler  1055.403770  1033.267363  1040.900072
3  Lasso permutation MinMaxScaler  1049.370481  1027.798426  1035.053759
4         Lasso Shap MinMaxScaler  1050.173022  1028.177913  1035.355058
5  ElasticNet optuna MinMaxScaler  1042.618016  1020.019125  1029.296690

                            model     train     valid      test
0              Lasso MinMaxScaler  0.581429  0.565065  0.588243
1        Lasso top10 MinMaxScaler  0.576784  0.560168  0.583558
2     Lasso selected MinMaxScaler  0.571261  0.553768  0.578982
3  Lasso permutation MinMaxScaler  0.576149  0.558479  0.583698
4         Lasso Shap MinMaxScaler  0.575500  0.558153  0.583455
5  ElasticNet optuna MinMaxScaler  0.581586  0.565138  0.588316

* Run optuna on one of the cross-validation schemes.

### Group K-Fold

In [63]:
def objective_groupkfold(trial, X, y, groups, n_splits=5):
  alpha = trial.suggest_float('alpha', 0.001, 10.0, log=True)
  l1_ratio = trial.suggest_float('l1_ratio', 0.0, 1.0)

  model = ElasticNet(alpha=alpha, l1_ratio=l1_ratio, random_state=21, max_iter=10000)

  gkf = GroupKFold(n_splits=n_splits)

  scores = []
  for train_idx, val_idx in gkf.split(X, y, groups):
    X_train_fold, X_val_fold = X[train_idx], X[val_idx]
    y_train_fold, y_val_fold = y.iloc[train_idx], y.iloc[val_idx]

    model.fit(X_train_fold, y_train_fold)
    score = r2_score(y_val_fold, model.predict(X_val_fold))
    scores.append(score)

  return np.mean(scores)

groups = X_train['bedrooms']

study = optuna.create_study(
    direction='maximize',
    sampler=TPESampler(seed=21)
)

study.optimize(
    lambda trial: objective_groupkfold(trial, X_train_scaled, y_train, groups),
    n_trials=100,
    show_progress_bar=True
)

[I 2026-04-09 19:04:07,138] A new study created in memory with name: no-name-5e0afddf-f9a5-4e1e-a742-c75b6444798a

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-09 19:04:08,597] Trial 0 finished with value: 0.2877636592433418 and parameters: {'alpha': 0.001566388634308505, 'l1_ratio': 0.28910965978981684}. Best is trial 0 with value: 0.2877636592433418.
[I 2026-04-09 19:04:08,764] Trial 1 finished with value: -1.0307634945312176 and parameters: {'alpha': 0.7653593415503201, 'l1_ratio': 0.021616249915949792}. Best is trial 0 with value: 0.2877636592433418.
[I 2026-04-09 19:04:09,455] Trial 2 finished with value: 0.21676706273682708 and parameters: {'alpha': 0.006663325994391817, 'l1_ratio': 0.0507732566953768}. Best is trial 0 with value: 0.2877636592433418.
[I 2026-04-09 19:04:12,978] Trial 3 finished with value: 0.2321460616927808 and parameters: {'alpha': 0.016184063577845232, 'l1_ratio': 0.6639102946247}. Best is trial 0 with value: 0.2877636592433418.
[I 2026-04-09 19:04:20,988] Trial 4 finished with value: 0.20250833836077975 and parameters: {'alpha': 0.017078808657853408, 'l1_ratio': 0.5835912762185987}. Best is trial 0 with value: 0.2877636592433418.
[I 2026-04-09 19:04:22,142] Trial 5 finished with value: 0.29108535746106295 and parameters: {'alpha': 0.0018979458542442303, 'l1_ratio': 0.8674044839930883}. Best is trial 5 with value: 0.29108535746106295.
[I 2026-04-09 19:04:23,092] Trial 6 finished with value: 0.2716908220347694 and parameters: {'alpha': 0.0034116311964428993, 'l1_ratio': 0.17812466155949835}. Best is trial 5 with value: 0.29108535746106295.
[I 2026-04-09 19:04:23,696] Trial 7 finished with value: 0.08909278060754555 and parameters: {'alpha': 0.09632038266656852, 'l1_ratio': 0.8636996445582236}. Best is trial 5 with value: 0.29108535746106295.
[I 2026-04-09 19:04:24,003] Trial 8 finished with value: -0.20380992979948784 and parameters: {'alpha': 1.0858637674408937, 'l1_ratio': 0.9704851253491577}. Best is trial 5 with value: 0.29108535746106295.
[I 2026-04-09 19:04:24,147] Trial 9 finished with value: -1.0181767273630737 and parameters: {'alpha': 1.089457294703886, 'l1_ratio': 0.3842500320901294}. Best is trial 5 with value: 0.29108535746106295.
[I 2026-04-09 19:04:24,604] Trial 10 finished with value: -0.10668845374290019 and parameters: {'alpha': 0.11587772057252048, 'l1_ratio': 0.7835931825968925}. Best is trial 5 with value: 0.29108535746106295.
[I 2026-04-09 19:04:26,402] Trial 11 finished with value: 0.2855737753682731 and parameters: {'alpha': 0.0023849266748819102, 'l1_ratio': 0.39973250796229964}. Best is trial 5 with value: 0.29108535746106295.
[I 2026-04-09 19:04:27,567] Trial 12 finished with value: 0.2897535558678963 and parameters: {'alpha': 0.0010123789735895707, 'l1_ratio': 0.27884866501765987}. Best is trial 5 with value: 0.29108535746106295.
[I 2026-04-09 19:04:28,783] Trial 13 finished with value: 0.290616650221445 and parameters: {'alpha': 0.0010468701483182397, 'l1_ratio': 0.5396389523356229}. Best is trial 5 with value: 0.29108535746106295.
[I 2026-04-09 19:04:29,217] Trial 14 finished with value: 0.02590225353971125 and parameters: {'alpha': 0.057286826194334756, 'l1_ratio': 0.7090655566963474}. Best is trial 5 with value: 0.29108535746106295.
[I 2026-04-09 19:04:29,441] Trial 15 finished with value: -1.1791682512544532 and parameters: {'alpha': 8.695490719982466, 'l1_ratio': 0.5359106125934296}. Best is trial 5 with value: 0.29108535746106295.
[I 2026-04-09 19:04:30,639] Trial 16 finished with value: 0.2912050254323722 and parameters: {'alpha': 0.009146586136227519, 'l1_ratio': 0.9892119511047284}. Best is trial 16 with value: 0.2912050254323722.
[I 2026-04-09 19:04:40,484] Trial 17 finished with value: 0.2912076440581751 and parameters: {'alpha': 0.008605990983240072, 'l1_ratio': 0.9958409935421333}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:04:41,152] Trial 18 finished with value: 0.29077489512001153 and parameters: {'alpha': 0.021968972002211977, 'l1_ratio': 0.9810467299339259}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:04:42,358] Trial 19 finished with value: 0.2888192156203654 and parameters: {'alpha': 0.007226044284866004, 'l1_ratio': 0.8716970517603246}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:04:42,746] Trial 20 finished with value: 0.15891769162750086 and parameters: {'alpha': 0.041879636266647896, 'l1_ratio': 0.7747095108565523}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:04:43,889] Trial 21 finished with value: 0.29120461711976864 and parameters: {'alpha': 0.006307491441547687, 'l1_ratio': 0.9962818934273124}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:04:44,743] Trial 22 finished with value: 0.2912069537365473 and parameters: {'alpha': 0.0065296937448112565, 'l1_ratio': 0.9861343176156924}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:04:45,039] Trial 23 finished with value: -0.12859222415050314 and parameters: {'alpha': 0.29626434856554384, 'l1_ratio': 0.9103387662307785}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:04:45,969] Trial 24 finished with value: 0.2792844067591269 and parameters: {'alpha': 0.009847606385719682, 'l1_ratio': 0.7836058810098432}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:04:47,901] Trial 25 finished with value: 0.2909849598404611 and parameters: {'alpha': 0.004135091208804592, 'l1_ratio': 0.9232172551488418}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:04:48,311] Trial 26 finished with value: 0.1415799172012848 and parameters: {'alpha': 0.03135357975215843, 'l1_ratio': 0.6697828226895035}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:04:49,125] Trial 27 finished with value: 0.28134306523839825 and parameters: {'alpha': 0.012310245289437072, 'l1_ratio': 0.843842884641599}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:04:49,705] Trial 28 finished with value: 0.2912065751249755 and parameters: {'alpha': 0.0822442635176199, 'l1_ratio': 0.9998272931384737}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:04:50,326] Trial 29 finished with value: -0.11433851698489247 and parameters: {'alpha': 0.35818260776147337, 'l1_ratio': 0.9288175467832728}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:04:51,344] Trial 30 finished with value: -0.12262540811408126 and parameters: {'alpha': 0.09061851347410842, 'l1_ratio': 0.7104852878818201}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:05:00,487] Trial 31 finished with value: 0.2911967058424604 and parameters: {'alpha': 0.0036876532715207164, 'l1_ratio': 0.9994500889920295}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:05:00,735] Trial 32 finished with value: 0.2307171398552597 and parameters: {'alpha': 0.028566603874304604, 'l1_ratio': 0.806769848796065}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:05:00,897] Trial 33 finished with value: 0.12185478277669796 and parameters: {'alpha': 0.190729127184705, 'l1_ratio': 0.9405284892265597}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:05:01,222] Trial 34 finished with value: 0.2890206248834959 and parameters: {'alpha': 0.00937935170959167, 'l1_ratio': 0.9053799730178225}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:05:01,334] Trial 35 finished with value: -0.7212224041734691 and parameters: {'alpha': 2.315766784895889, 'l1_ratio': 0.94142095983546}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:05:01,601] Trial 36 finished with value: 0.17112071412032506 and parameters: {'alpha': 0.05371204488667288, 'l1_ratio': 0.8364247909142712}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:05:01,870] Trial 37 finished with value: 0.24326671517785942 and parameters: {'alpha': 0.01769580350962425, 'l1_ratio': 0.7305091713578558}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:05:02,248] Trial 38 finished with value: 0.29113739889009765 and parameters: {'alpha': 0.0018539447509566894, 'l1_ratio': 0.8887015524277186}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:05:02,675] Trial 39 finished with value: 0.27106235137602297 and parameters: {'alpha': 0.0031415902582649464, 'l1_ratio': 0.09126302730550179}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:05:03,005] Trial 40 finished with value: 0.2799326501353964 and parameters: {'alpha': 0.0053413527994547036, 'l1_ratio': 0.6128328058927003}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:05:03,353] Trial 41 finished with value: 0.2912034966150645 and parameters: {'alpha': 0.005821149992150338, 'l1_ratio': 0.9966076366432478}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:05:03,707] Trial 42 finished with value: 0.29062699112143636 and parameters: {'alpha': 0.011980733741386994, 'l1_ratio': 0.9602585447609799}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:05:04,050] Trial 43 finished with value: 0.2912003468518544 and parameters: {'alpha': 0.007737624940602396, 'l1_ratio': 0.9853248129067016}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:05:04,341] Trial 44 finished with value: 0.2742313227895048 and parameters: {'alpha': 0.01687368419857813, 'l1_ratio': 0.8465564766351847}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:05:04,738] Trial 45 finished with value: 0.2911950696170867 and parameters: {'alpha': 0.0026949502782468355, 'l1_ratio': 0.9529257938864786}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:05:05,070] Trial 46 finished with value: 0.2721162049588033 and parameters: {'alpha': 0.005042905604296871, 'l1_ratio': 0.45094872606351466}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:05:05,452] Trial 47 finished with value: 0.29117348126869513 and parameters: {'alpha': 0.0014641077475968575, 'l1_ratio': 0.887910499044438}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:05:05,645] Trial 48 finished with value: 0.012152187350544907 and parameters: {'alpha': 0.025318693699755285, 'l1_ratio': 0.3095896294798228}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:05:05,855] Trial 49 finished with value: 0.07627026115303485 and parameters: {'alpha': 0.07482121197281978, 'l1_ratio': 0.8151091173280101}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:05:06,133] Trial 50 finished with value: 0.28465929591381056 and parameters: {'alpha': 0.03780745345386832, 'l1_ratio': 0.9592395856237826}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:05:06,458] Trial 51 finished with value: 0.2912002389593979 and parameters: {'alpha': 0.012654649830422575, 'l1_ratio': 0.9993564310531116}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:05:06,796] Trial 52 finished with value: 0.2901277268769788 and parameters: {'alpha': 0.0056908433938187225, 'l1_ratio': 0.8886579131554408}. Best is trial 17 with value: 0.2912076440581751.
[I 2026-04-09 19:05:07,155] Trial 53 finished with value: 0.2912098716882997 and parameters: {'alpha': 0.007123690662857487, 'l1_ratio': 0.9907929353230985}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:07,489] Trial 54 finished with value: 0.2900205281173278 and parameters: {'alpha': 0.00821871806407036, 'l1_ratio': 0.9194651060498792}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:07,857] Trial 55 finished with value: 0.29119483248215106 and parameters: {'alpha': 0.0026020406264384284, 'l1_ratio': 0.9510412637157338}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:08,041] Trial 56 finished with value: -0.004592474680786873 and parameters: {'alpha': 0.13471332035429645, 'l1_ratio': 0.8631998147559952}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:08,387] Trial 57 finished with value: 0.2844623867656464 and parameters: {'alpha': 0.019827993872385628, 'l1_ratio': 0.9208698533545377}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:08,729] Trial 58 finished with value: 0.2882647154331638 and parameters: {'alpha': 0.00418753405863828, 'l1_ratio': 0.7543324658076511}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:09,094] Trial 59 finished with value: 0.29082199578774803 and parameters: {'alpha': 0.012878944925197956, 'l1_ratio': 0.969118157815404}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:09,492] Trial 60 finished with value: 0.29108896187705574 and parameters: {'alpha': 0.00130253927516976, 'l1_ratio': 0.8088653309013094}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:09,854] Trial 61 finished with value: 0.2911979924632942 and parameters: {'alpha': 0.002306912602760971, 'l1_ratio': 0.9976321565566741}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:10,219] Trial 62 finished with value: 0.2912067176200906 and parameters: {'alpha': 0.008930670516379547, 'l1_ratio': 0.9965234787091312}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:10,929] Trial 63 finished with value: 0.28985860323000195 and parameters: {'alpha': 0.0072505943634878535, 'l1_ratio': 0.9029916558732682}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:13,287] Trial 64 finished with value: 0.29116095310896856 and parameters: {'alpha': 0.004167032190619494, 'l1_ratio': 0.9567795850542726}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:14,123] Trial 65 finished with value: 0.28628546820718354 and parameters: {'alpha': 0.01033908800048717, 'l1_ratio': 0.8710197483354488}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:14,397] Trial 66 finished with value: -0.18606574273580295 and parameters: {'alpha': 0.40494868985126814, 'l1_ratio': 0.9234983429957768}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:14,910] Trial 67 finished with value: -0.28384392735416186 and parameters: {'alpha': 1.9577324424503955, 'l1_ratio': 0.9801399019556374}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:20,547] Trial 68 finished with value: 0.28529269855823297 and parameters: {'alpha': 0.02336791117463356, 'l1_ratio': 0.9373514893609327}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:20,840] Trial 69 finished with value: 0.27524644975503476 and parameters: {'alpha': 0.014834099238196183, 'l1_ratio': 0.8313465508831146}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:21,213] Trial 70 finished with value: 0.2910036680125791 and parameters: {'alpha': 0.009364084584333812, 'l1_ratio': 0.9673681686743696}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:21,564] Trial 71 finished with value: 0.291196476953702 and parameters: {'alpha': 0.005970535865505485, 'l1_ratio': 0.9998566186200152}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:21,889] Trial 72 finished with value: 0.29115616592743976 and parameters: {'alpha': 0.006855638410515676, 'l1_ratio': 0.9729573315258508}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:22,272] Trial 73 finished with value: 0.2909595280229038 and parameters: {'alpha': 0.0034955697333900965, 'l1_ratio': 0.9050443621719402}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:22,607] Trial 74 finished with value: 0.29100827883619457 and parameters: {'alpha': 0.004821679276463042, 'l1_ratio': 0.9370423584414274}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:23,054] Trial 75 finished with value: 0.28076754139302096 and parameters: {'alpha': 0.0019987860539208654, 'l1_ratio': 0.007272227762102623}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:23,441] Trial 76 finished with value: 0.2908205261553479 and parameters: {'alpha': 0.0031047343300907794, 'l1_ratio': 0.8711147005824843}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:23,600] Trial 77 finished with value: -0.14062106864278784 and parameters: {'alpha': 0.03409911224732559, 'l1_ratio': 0.1905304585712273}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:23,909] Trial 78 finished with value: 0.2909021758345907 and parameters: {'alpha': 0.015317142952587435, 'l1_ratio': 0.9765167061227956}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:24,025] Trial 79 finished with value: -0.049467746670009596 and parameters: {'alpha': 7.6689237664268415, 'l1_ratio': 0.9977236183166246}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:24,315] Trial 80 finished with value: 0.2679565537032889 and parameters: {'alpha': 0.05160835718125017, 'l1_ratio': 0.9401672265894399}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:24,645] Trial 81 finished with value: 0.2911807007972448 and parameters: {'alpha': 0.008206773457353366, 'l1_ratio': 0.9814168338554694}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:24,961] Trial 82 finished with value: 0.2899508982220266 and parameters: {'alpha': 0.006572257852964487, 'l1_ratio': 0.896495519412611}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:25,317] Trial 83 finished with value: 0.2905384848494886 and parameters: {'alpha': 0.010966127244272145, 'l1_ratio': 0.9537078966757327}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:25,668] Trial 84 finished with value: 0.2912055412038755 and parameters: {'alpha': 0.004926299143416143, 'l1_ratio': 0.9803465558677227}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:26,003] Trial 85 finished with value: 0.2907956197133835 and parameters: {'alpha': 0.005100009401505825, 'l1_ratio': 0.9194743727772535}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:26,408] Trial 86 finished with value: 0.2911971063682173 and parameters: {'alpha': 0.004102566986134104, 'l1_ratio': 0.9702431725101814}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:26,692] Trial 87 finished with value: 0.27042149438382773 and parameters: {'alpha': 0.019927254896133215, 'l1_ratio': 0.8543455926024619}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:26,805] Trial 88 finished with value: -0.8255064233144473 and parameters: {'alpha': 0.5727913904228449, 'l1_ratio': 0.6312847350930764}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:27,107] Trial 89 finished with value: 0.25165797499999043 and parameters: {'alpha': 0.008974064361783954, 'l1_ratio': 0.5276181283536817}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:27,317] Trial 90 finished with value: 0.16484387723009664 and parameters: {'alpha': 0.15364070224422677, 'l1_ratio': 0.9408545988342131}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:27,716] Trial 91 finished with value: 0.2911965852748632 and parameters: {'alpha': 0.006669111205393384, 'l1_ratio': 0.9998642686374898}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:28,046] Trial 92 finished with value: 0.2911999995612756 and parameters: {'alpha': 0.008060002837173333, 'l1_ratio': 0.9857997196249076}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:28,373] Trial 93 finished with value: 0.29035960945048533 and parameters: {'alpha': 0.013823669830143864, 'l1_ratio': 0.9591306296296812}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:28,808] Trial 94 finished with value: 0.2909468605663608 and parameters: {'alpha': 0.0031297012605061153, 'l1_ratio': 0.8917297449440705}. Best is trial 53 with value: 0.2912098716882997.
[I 2026-04-09 19:05:29,155] Trial 95 finished with value: 0.29077622533894026 and parameters: {'alpha': 0.005349736536312357, 'l1_ratio': 0.9216973085286208}. Best is trial 53 with value: 0.2912098716882997.

In [65]:
trial = study.best_trial

elastic_model = ElasticNet(**trial.params)

mae, rmse, r2 = get_metrics(elastic_model, X_train_scaled, X_val_scaled, X_test_scaled, y_train, y_val, y_test, 'ElasticNet optuna GroupKFold')

mae_optuna.append(mae)

rmse_optuna.append(rmse)

r2_optuna.append(r2)

### TimeSeriesSplit

In [68]:
def objective_timeseries(trial, X, y, n_splits=5):
  alpha = trial.suggest_float('alpha', 0.001, 10.0, log=True)
  l1_ratio = trial.suggest_float('l1_ratio', 0.0, 1.0)

  model = ElasticNet(alpha=alpha, l1_ratio=l1_ratio, random_state=42, max_iter=10000)

  tscv = TimeSeriesSplit(n_splits=n_splits)

  scores = []
  for train_idx, val_idx in tscv.split(X):
    X_train_fold, X_val_fold = X[train_idx], X[val_idx]
    y_train_fold, y_val_fold = y.iloc[train_idx], y.iloc[val_idx]

    model.fit(X_train_fold, y_train_fold)
    score = r2_score(y_val_fold, model.predict(X_val_fold))
    scores.append(score)

  return np.mean(scores)

study = optuna.create_study(
    direction='maximize',
    sampler=TPESampler(seed=21)
)

study.optimize(
    lambda trial: objective_timeseries(trial, X_train_scaled, y_train),
    n_trials=100,
    show_progress_bar=True
)

[I 2026-04-09 19:19:42,686] A new study created in memory with name: no-name-f5a97580-def4-4374-830d-660853e5a88e

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-09 19:19:42,935] Trial 0 finished with value: 0.582147320554042 and parameters: {'alpha': 0.001566388634308505, 'l1_ratio': 0.28910965978981684}. Best is trial 0 with value: 0.582147320554042.
[I 2026-04-09 19:19:43,008] Trial 1 finished with value: 0.11840575421747808 and parameters: {'alpha': 0.7653593415503201, 'l1_ratio': 0.021616249915949792}. Best is trial 0 with value: 0.582147320554042.
[I 2026-04-09 19:19:43,239] Trial 2 finished with value: 0.5597358193131572 and parameters: {'alpha': 0.006663325994391817, 'l1_ratio': 0.0507732566953768}. Best is trial 0 with value: 0.582147320554042.
[I 2026-04-09 19:19:43,410] Trial 3 finished with value: 0.5644344199093951 and parameters: {'alpha': 0.016184063577845232, 'l1_ratio': 0.6639102946247}. Best is trial 0 with value: 0.582147320554042.
[I 2026-04-09 19:19:43,566] Trial 4 finished with value: 0.555414156051636 and parameters: {'alpha': 0.017078808657853408, 'l1_ratio': 0.5835912762185987}. Best is trial 0 with value: 0.582147320554042.
[I 2026-04-09 19:19:43,786] Trial 5 finished with value: 0.5833673554257708 and parameters: {'alpha': 0.0018979458542442303, 'l1_ratio': 0.8674044839930883}. Best is trial 5 with value: 0.5833673554257708.
[I 2026-04-09 19:19:44,008] Trial 6 finished with value: 0.576806365302761 and parameters: {'alpha': 0.0034116311964428993, 'l1_ratio': 0.17812466155949835}. Best is trial 5 with value: 0.5833673554257708.
[I 2026-04-09 19:19:44,121] Trial 7 finished with value: 0.5213980899939811 and parameters: {'alpha': 0.09632038266656852, 'l1_ratio': 0.8636996445582236}. Best is trial 5 with value: 0.5833673554257708.
[I 2026-04-09 19:19:44,238] Trial 8 finished with value: 0.4318574880635371 and parameters: {'alpha': 1.0858637674408937, 'l1_ratio': 0.9704851253491577}. Best is trial 5 with value: 0.5833673554257708.
[I 2026-04-09 19:19:44,306] Trial 9 finished with value: 0.12498603793519625 and parameters: {'alpha': 1.089457294703886, 'l1_ratio': 0.3842500320901294}. Best is trial 5 with value: 0.5833673554257708.
[I 2026-04-09 19:19:44,392] Trial 10 finished with value: 0.4619801434452178 and parameters: {'alpha': 0.11587772057252048, 'l1_ratio': 0.7835931825968925}. Best is trial 5 with value: 0.5833673554257708.
[I 2026-04-09 19:19:44,617] Trial 11 finished with value: 0.5813909492299031 and parameters: {'alpha': 0.0023849266748819102, 'l1_ratio': 0.39973250796229964}. Best is trial 5 with value: 0.5833673554257708.
[I 2026-04-09 19:19:44,870] Trial 12 finished with value: 0.5828558380825929 and parameters: {'alpha': 0.0010123789735895707, 'l1_ratio': 0.27884866501765987}. Best is trial 5 with value: 0.5833673554257708.
[I 2026-04-09 19:19:45,115] Trial 13 finished with value: 0.5831779183432563 and parameters: {'alpha': 0.0010468701483182397, 'l1_ratio': 0.5396389523356229}. Best is trial 5 with value: 0.5833673554257708.
[I 2026-04-09 19:19:45,272] Trial 14 finished with value: 0.5023903364771861 and parameters: {'alpha': 0.057286826194334756, 'l1_ratio': 0.7090655566963474}. Best is trial 5 with value: 0.5833673554257708.
[I 2026-04-09 19:19:45,342] Trial 15 finished with value: 0.037911189768401264 and parameters: {'alpha': 8.695490719982466, 'l1_ratio': 0.5359106125934296}. Best is trial 5 with value: 0.5833673554257708.
[I 2026-04-09 19:19:45,536] Trial 16 finished with value: 0.583429398772261 and parameters: {'alpha': 0.009146586136227519, 'l1_ratio': 0.9892119511047284}. Best is trial 16 with value: 0.583429398772261.
[I 2026-04-09 19:19:45,741] Trial 17 finished with value: 0.583438644454444 and parameters: {'alpha': 0.008605990983240072, 'l1_ratio': 0.9958409935421333}. Best is trial 17 with value: 0.583438644454444.
[I 2026-04-09 19:19:45,927] Trial 18 finished with value: 0.5832428337151068 and parameters: {'alpha': 0.021968972002211977, 'l1_ratio': 0.9810467299339259}. Best is trial 17 with value: 0.583438644454444.
[I 2026-04-09 19:19:46,128] Trial 19 finished with value: 0.5825206116342952 and parameters: {'alpha': 0.007226044284866004, 'l1_ratio': 0.8716970517603246}. Best is trial 17 with value: 0.583438644454444.
[I 2026-04-09 19:19:46,287] Trial 20 finished with value: 0.5423023658140265 and parameters: {'alpha': 0.041879636266647896, 'l1_ratio': 0.7747095108565523}. Best is trial 17 with value: 0.583438644454444.
[I 2026-04-09 19:19:46,506] Trial 21 finished with value: 0.5834390546003394 and parameters: {'alpha': 0.006307491441547687, 'l1_ratio': 0.9962818934273124}. Best is trial 21 with value: 0.5834390546003394.
[I 2026-04-09 19:19:46,727] Trial 22 finished with value: 0.5834308948639381 and parameters: {'alpha': 0.0065296937448112565, 'l1_ratio': 0.9861343176156924}. Best is trial 21 with value: 0.5834390546003394.
[I 2026-04-09 19:19:46,945] Trial 23 finished with value: 0.5832684331986002 and parameters: {'alpha': 0.004420721138997192, 'l1_ratio': 0.9121856486181052}. Best is trial 21 with value: 0.5834390546003394.
[I 2026-04-09 19:19:47,107] Trial 24 finished with value: 0.5621274100721205 and parameters: {'alpha': 0.02714870863914764, 'l1_ratio': 0.7836058810098432}. Best is trial 21 with value: 0.5834390546003394.
[I 2026-04-09 19:19:47,200] Trial 25 finished with value: 0.48848322085456497 and parameters: {'alpha': 0.2520319081161974, 'l1_ratio': 0.9233261847438927}. Best is trial 21 with value: 0.5834390546003394.
[I 2026-04-09 19:19:47,414] Trial 26 finished with value: 0.5743556873829185 and parameters: {'alpha': 0.010397461802359866, 'l1_ratio': 0.6738798113189107}. Best is trial 21 with value: 0.5834390546003394.
[I 2026-04-09 19:19:47,631] Trial 27 finished with value: 0.5830249396167347 and parameters: {'alpha': 0.003915688884767581, 'l1_ratio': 0.8440247804160519}. Best is trial 21 with value: 0.5834390546003394.
[I 2026-04-09 19:19:47,781] Trial 28 finished with value: 0.5834540940121931 and parameters: {'alpha': 0.2667320458424261, 'l1_ratio': 0.9998272931384737}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:19:47,879] Trial 29 finished with value: 0.3095392805945987 and parameters: {'alpha': 0.36231900170786463, 'l1_ratio': 0.7608447760468185}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:19:47,946] Trial 30 finished with value: 0.23837512141475453 and parameters: {'alpha': 2.3844370206086833, 'l1_ratio': 0.9333417795085507}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:19:48,267] Trial 31 finished with value: 0.5834379511358643 and parameters: {'alpha': 0.20208971726872954, 'l1_ratio': 0.9994675811221742}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:19:48,664] Trial 32 finished with value: 0.5830177959480102 and parameters: {'alpha': 0.24680598764227235, 'l1_ratio': 0.9975852795299656}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:19:49,327] Trial 33 finished with value: 0.39989581660336854 and parameters: {'alpha': 0.4458216263627169, 'l1_ratio': 0.9056450488563279}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:19:50,344] Trial 34 finished with value: 0.45962365224303864 and parameters: {'alpha': 0.13468802651599648, 'l1_ratio': 0.8098404200322218}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:19:50,516] Trial 35 finished with value: 0.2403267620906182 and parameters: {'alpha': 2.332811397575529, 'l1_ratio': 0.9331092610687989}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:19:50,881] Trial 36 finished with value: 0.5558331314395055 and parameters: {'alpha': 0.04331252015995414, 'l1_ratio': 0.8376989075286099}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:19:51,061] Trial 37 finished with value: 0.3795353505032391 and parameters: {'alpha': 0.17867504588829528, 'l1_ratio': 0.7221373359835677}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:19:53,382] Trial 38 finished with value: 0.5515660133612685 and parameters: {'alpha': 0.06990027837453823, 'l1_ratio': 0.8885683903219954}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:19:54,311] Trial 39 finished with value: 0.20759663949016693 and parameters: {'alpha': 0.6066280013727273, 'l1_ratio': 0.6287816295354163}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:19:56,321] Trial 40 finished with value: 0.582440503781747 and parameters: {'alpha': 0.01527307667797978, 'l1_ratio': 0.9365804361296839}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:19:57,568] Trial 41 finished with value: 0.5834388589213506 and parameters: {'alpha': 0.002296081182663731, 'l1_ratio': 0.9966159605790668}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:19:58,322] Trial 42 finished with value: 0.5834232239662932 and parameters: {'alpha': 0.002425748840063311, 'l1_ratio': 0.9501303256445212}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:19:58,558] Trial 43 finished with value: 0.5833449490672732 and parameters: {'alpha': 0.0018070577709166549, 'l1_ratio': 0.8406107680311451}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:19:58,770] Trial 44 finished with value: 0.570416021695771 and parameters: {'alpha': 0.004986504133821337, 'l1_ratio': 0.14766373571664304}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:19:59,001] Trial 45 finished with value: 0.5834388043584883 and parameters: {'alpha': 0.002876230483615403, 'l1_ratio': 0.9936020196641888}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:19:59,284] Trial 46 finished with value: 0.5834130233070207 and parameters: {'alpha': 0.00138156174457458, 'l1_ratio': 0.8890734335082974}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:19:59,512] Trial 47 finished with value: 0.5820435615747372 and parameters: {'alpha': 0.0021487891756152406, 'l1_ratio': 0.4597232378753578}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:19:59,733] Trial 48 finished with value: 0.5834136674203636 and parameters: {'alpha': 0.003319562320836556, 'l1_ratio': 0.9542608352007009}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:19:59,955] Trial 49 finished with value: 0.5830205966822614 and parameters: {'alpha': 0.0033566701520451967, 'l1_ratio': 0.8170542383711057}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:00,151] Trial 50 finished with value: 0.5816638032401482 and parameters: {'alpha': 0.011617429095878361, 'l1_ratio': 0.8861727024606146}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:00,349] Trial 51 finished with value: 0.5834437317900377 and parameters: {'alpha': 0.09123390165647696, 'l1_ratio': 0.9993430594762853}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:00,558] Trial 52 finished with value: 0.5833681196111602 and parameters: {'alpha': 0.006167351353493882, 'l1_ratio': 0.9593585154627362}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:00,790] Trial 53 finished with value: 0.5834361994783276 and parameters: {'alpha': 0.0013766275168632426, 'l1_ratio': 0.9610206852766008}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:00,943] Trial 54 finished with value: 0.49748381031581246 and parameters: {'alpha': 0.018036066674710412, 'l1_ratio': 0.02260972075659501}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:01,171] Trial 55 finished with value: 0.5834388914597127 and parameters: {'alpha': 0.0026020406264384284, 'l1_ratio': 0.9959282284394922}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:01,424] Trial 56 finished with value: 0.5789891339771998 and parameters: {'alpha': 0.002986934292956275, 'l1_ratio': 0.2574656113543383}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:01,683] Trial 57 finished with value: 0.5834069531857329 and parameters: {'alpha': 0.0012931984329889192, 'l1_ratio': 0.8688282688560219}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:01,761] Trial 58 finished with value: 0.32576508020271167 and parameters: {'alpha': 0.8629039332454148, 'l1_ratio': 0.9127851298735886}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:01,936] Trial 59 finished with value: 0.582339639167998 and parameters: {'alpha': 0.03214949173657277, 'l1_ratio': 0.9683324001485928}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:02,107] Trial 60 finished with value: 0.5831009252753558 and parameters: {'alpha': 0.08347096728002058, 'l1_ratio': 0.9934618010858544}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:02,332] Trial 61 finished with value: 0.5832434529050021 and parameters: {'alpha': 0.0054783202788956185, 'l1_ratio': 0.9240707720022713}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:02,574] Trial 62 finished with value: 0.583439089124257 and parameters: {'alpha': 0.008386029675261636, 'l1_ratio': 0.9966503173634033}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:02,798] Trial 63 finished with value: 0.5834240064785813 and parameters: {'alpha': 0.002371240761781241, 'l1_ratio': 0.9502049206943342}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:03,002] Trial 64 finished with value: 0.5833237194402268 and parameters: {'alpha': 0.012425361908743505, 'l1_ratio': 0.9743183131351486}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:03,222] Trial 65 finished with value: 0.5830381101040235 and parameters: {'alpha': 0.004259762133437468, 'l1_ratio': 0.8590050081554537}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:03,497] Trial 66 finished with value: 0.5834292001341822 and parameters: {'alpha': 0.0010522228877209664, 'l1_ratio': 0.9086545597319781}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:03,708] Trial 67 finished with value: 0.5834102100322203 and parameters: {'alpha': 0.008150688327407599, 'l1_ratio': 0.9800777161076233}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:03,945] Trial 68 finished with value: 0.583438760012938 and parameters: {'alpha': 0.001704492158612049, 'l1_ratio': 0.9976470489227217}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:04,081] Trial 69 finished with value: 0.5495699251346786 and parameters: {'alpha': 0.11573869208564684, 'l1_ratio': 0.9297371246414483}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:04,314] Trial 70 finished with value: 0.5805523074170718 and parameters: {'alpha': 0.0027888728684002844, 'l1_ratio': 0.3786101347944224}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:04,581] Trial 71 finished with value: 0.5834387108532427 and parameters: {'alpha': 0.001790466218772213, 'l1_ratio': 0.9998611472195496}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:04,815] Trial 72 finished with value: 0.5834348369134374 and parameters: {'alpha': 0.0017558348812944124, 'l1_ratio': 0.9630962518163821}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:05,040] Trial 73 finished with value: 0.5832108704308266 and parameters: {'alpha': 0.004194025536426989, 'l1_ratio': 0.8927454146751478}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:05,242] Trial 74 finished with value: 0.5832083792930998 and parameters: {'alpha': 0.007173027472426433, 'l1_ratio': 0.9369507668892649}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:05,329] Trial 75 finished with value: 0.5530028142903959 and parameters: {'alpha': 1.5869052423110055, 'l1_ratio': 0.9954987545611605}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:05,409] Trial 76 finished with value: 0.3619170128502699 and parameters: {'alpha': 0.3223246497813145, 'l1_ratio': 0.8234499538663262}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:05,669] Trial 77 finished with value: 0.583292596944853 and parameters: {'alpha': 0.0026618349713261407, 'l1_ratio': 0.864965895577112}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:05,756] Trial 78 finished with value: 0.390529462036236 and parameters: {'alpha': 0.5200055949586757, 'l1_ratio': 0.9129607392210941}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:05,819] Trial 79 finished with value: 0.06390382554093658 and parameters: {'alpha': 7.6689237664268415, 'l1_ratio': 0.7414933538668059}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:06,072] Trial 80 finished with value: 0.5834383060321506 and parameters: {'alpha': 0.001021611709754049, 'l1_ratio': 0.9742836055396629}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:06,308] Trial 81 finished with value: 0.583426099848169 and parameters: {'alpha': 0.001973778000254942, 'l1_ratio': 0.9443485930204434}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:06,552] Trial 82 finished with value: 0.5834387130751816 and parameters: {'alpha': 0.0015139439885684144, 'l1_ratio': 0.9902993042092512}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:06,828] Trial 83 finished with value: 0.5834373669002973 and parameters: {'alpha': 0.001397659896881958, 'l1_ratio': 0.9701485164553215}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:07,055] Trial 84 finished with value: 0.5834389747532813 and parameters: {'alpha': 0.003794530958089246, 'l1_ratio': 0.9958428251977397}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:07,284] Trial 85 finished with value: 0.5833469368207005 and parameters: {'alpha': 0.005086684942719833, 'l1_ratio': 0.943943478145244}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:07,518] Trial 86 finished with value: 0.583278040159478 and parameters: {'alpha': 0.0033979905301954097, 'l1_ratio': 0.8890474115979146}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:07,757] Trial 87 finished with value: 0.5799323931139305 and parameters: {'alpha': 0.009559602303867357, 'l1_ratio': 0.7977279455266916}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:07,988] Trial 88 finished with value: 0.5834389525416297 and parameters: {'alpha': 0.0036942056748232176, 'l1_ratio': 0.9999640091783144}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:08,207] Trial 89 finished with value: 0.5831366678741333 and parameters: {'alpha': 0.005883397337640753, 'l1_ratio': 0.9117281856770041}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:08,633] Trial 90 finished with value: 0.5829803698314944 and parameters: {'alpha': 0.014288937555806184, 'l1_ratio': 0.9549752138524176}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:09,136] Trial 91 finished with value: 0.5834389686618551 and parameters: {'alpha': 0.003769821053174721, 'l1_ratio': 0.9998788762479313}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:10,982] Trial 92 finished with value: 0.5834177054422668 and parameters: {'alpha': 0.003488254245148984, 'l1_ratio': 0.9599234909847657}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:11,479] Trial 93 finished with value: 0.5834244094258414 and parameters: {'alpha': 0.0045004668812217465, 'l1_ratio': 0.9739427894264647}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:11,902] Trial 94 finished with value: 0.583149890296921 and parameters: {'alpha': 0.007705036315550929, 'l1_ratio': 0.9341326717689089}. Best is trial 28 with value: 0.5834540940121931.
[I 2026-04-09 19:20:13,264] Trial 95 finished with value: 0.5728965743324526 and parameters: {'alpha': 0.1656648097984781, 'l1_ratio': 0.9777274211738136}. Best is trial 28 with value: 0.5834540940121931.

In [69]:
trial = study.best_trial

elastic_model = ElasticNet(**trial.params)

mae, rmse, r2 = get_metrics(elastic_model, X_train_scaled, X_val_scaled, X_test_scaled, y_train, y_val, y_test, 'ElasticNet optuna TimeSeriesSplit')

mae_optuna.append(mae)

rmse_optuna.append(rmse)

r2_optuna.append(r2)

### Results

In [70]:
display(pd.DataFrame(mae_optuna))
display(pd.DataFrame(rmse_optuna))
display(pd.DataFrame(r2_optuna))

                               model       train       valid        test
0     ElasticNet optuna MinMaxScaler  718.283708  700.124746  708.777220
1       ElasticNet optuna GroupKFold  718.295393  700.123813  708.797102
2  ElasticNet optuna TimeSeriesSplit  718.188507  699.936753  708.698962

                               model        train        valid         test
0     ElasticNet optuna MinMaxScaler  1042.618016  1020.019125  1029.296690
1       ElasticNet optuna GroupKFold  1042.622839  1019.958835  1029.331516
2  ElasticNet optuna TimeSeriesSplit  1042.641138  1019.990267  1029.331801

                               model     train     valid      test
0     ElasticNet optuna MinMaxScaler  0.581586  0.565138  0.588316
1       ElasticNet optuna GroupKFold  0.581582  0.565189  0.588288
2  ElasticNet optuna TimeSeriesSplit  0.581568  0.565162  0.588288